
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin1",
    "password":"123",
    "unit_id":"e8d970d2-59cf-4a1f-98d0-5a14262362e9"
}
###


GET {{HOSTAPI}}/api/ctb/ctbconta HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###


POST {{HOSTAPI}}/api/ctb/ctbconta HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
  "ativo": "S",
  "ctb_conta_grupo_id": "4dd5cd41-ce4e-4368-bd58-6d5df569a3a9",
  "ctb_conta_versao_id": "aa326481-8445-42c2-80e5-420b4251cb0c",
  "nome": "tst",
  "sigla_conta": "tst",
  "tipo_conta": "1",
  "tipo_dc": "D",
  "tipo_variacao": "F",
  "unit_id":"e8d970d2-59cf-4a1f-98d0-5a14262362e9"
  
}


### 




