DROP VIEW IF EXISTS vwbor_bor_mov_line;
CREATE OR replace VIEW public.vwbor_bor_mov_line
AS select a.id,
	a.id_tipo,
	a.numero_serie,
	a.ibutton_rfid,
	a.dthr_track,
	a.gps_altitude,
	a.gps_altitude_status,
	a.gps_lat,
	a.gps_long,
	a.gps_angulo_norte,
	a.gps_posicao_status,
	a.gps_velocidade,
	a.gps_velocidade_media,
	a.equipamento_ignicao,
	a.equipamento_bateria,
	a.equipamento_odometro,
	a.equipamento_rpm,
	a.equipamento_veloc,
	a.equipamento_veloc_odom,
	a.equipamento_veloc_odom_media,
	a.log_user_ins,
	a.log_date_ins,
	a.log_user_upd,
	a.log_date_upd,
	a.ope_centro2_equip_id_1,
	a.ope_centro2_equip_id_2,
	a.ope_centro2_pessoa_id,
	a.ger_empresa_id,
	a.ope_centro2_area_id,
	a.buzzer,
	a.unit_id,
		st_setsrid(st_makeline(st_geomfromtext(((('POINT('::text || a.gps_lat::text) || ' '::text) || a.gps_long::text) || ')'::text), lag(st_geomfromtext(((('POINT('::text || a.gps_lat::text) || ' '::text) || a.gps_long::text) || ')'::text)) OVER (ORDER BY a.numero_serie, a.dthr_track)), 4326) AS line
	 FROM bor_mov a
	GROUP BY a.id,
	a.id_tipo,
	a.numero_serie,
	a.ibutton_rfid,
	a.dthr_track,
	a.gps_altitude,
	a.gps_altitude_status,
	a.gps_lat,
	a.gps_long,
	a.gps_angulo_norte,
	a.gps_posicao_status,
	a.gps_velocidade,
	a.gps_velocidade_media,
	a.equipamento_ignicao,
	a.equipamento_bateria,
	a.equipamento_odometro,
	a.equipamento_rpm,
	a.equipamento_veloc,
	a.equipamento_veloc_odom,
	a.equipamento_veloc_odom_media,
	a.log_user_ins,
	a.log_date_ins,
	a.log_user_upd,
	a.log_date_upd,
	a.ope_centro2_equip_id_1,
	a.ope_centro2_equip_id_2,
	a.ope_centro2_pessoa_id,
	a.ger_empresa_id,
	a.ope_centro2_area_id,
	a.buzzer,
	a.unit_id;