CREATE OR REPLACE VIEW public.vwmov_mov_itemserv
AS SELECT t1.unit_id AS mov_itemserv_unit_id,
    t1.id AS mov_itemserv_id,
    t1.mov_id AS mov_itemserv_mov_id,
    t1.ger_itemserv_id AS mov_itemserv_ger_itemserv_id,
    t1.qnt_orig AS mov_itemserv_qnt_orig,
    t1.valor_unit_orig AS mov_itemserv_valor_unit_orig,
    t1.ger_umedida_id_conv AS mov_itemserv_ger_umedida_id_conv,
    t1.qnt_conv AS mov_itemserv_qnt_conv,
    t1.valor_unit_conv AS mov_itemserv_valor_unit_conv,
    t1.valor_bruto AS mov_itemserv_valor_bruto,
    t1.valor_desconto AS mov_itemserv_valor_desconto,
    t1.valor_acrecimo AS mov_itemserv_valor_acrecimo,
    t1.valor_outros AS mov_itemserv_valor_outros,
    t1.valor_liquido AS mov_itemserv_valor_liquido,
    t1.qnt_devolvida AS mov_itemserv_qnt_devolvida,
    t1.valor_frete AS mov_itemserv_valor_frete,
    t1.valor_seguro AS mov_itemserv_valor_seguro,
    t1.observacao AS mov_itemserv_observacao,
    t1.valor_tributo_retido AS mov_itemserv_valor_tributo_retido,
    t1.fis_cfop_id AS mov_itemserv_fis_cfop_id,
    t1.valor_tributo_total AS mov_itemserv_valor_tributo_total,
    t1.qnt_altura AS mov_itemserv_qnt_altura,
    t1.qnt_largura AS mov_itemserv_qnt_largura,
    t1.qnt_comprimento AS mov_itemserv_qnt_comprimento,
    t1.nome_itemserv AS mov_itemserv_nome_itemserv,
    t1.ger_itemserv_var_id AS mov_itemserv_ger_itemserv_var_id,
    t1.ger_itemserv_lote_id AS mov_itemserv_ger_itemserv_lote_id,
    t1.fis_obra_art AS mov_itemserv_fis_obra_art,
    t1.fis_obra_cei AS mov_itemserv_fis_obra_cei,
    t1.fis_numero_proc_susp_nfs AS mov_itemserv_fis_numero_proc_susp_nfs,
    t1.fis_doc_cnae_nfs AS mov_itemserv_fis_doc_cnae_nfs,
    t1.valor_outros_tributo_ret AS mov_itemserv_valor_outros_tributo_ret,
    t1.valor_desconto_cond AS mov_itemserv_valor_desconto_cond,
    t1.valor_desconto_incond AS mov_itemserv_valor_desconto_incond,
    t1.valor_deducao AS mov_itemserv_valor_deducao,
    t1.qnt_min_pessoa_cot AS mov_itemserv_qnt_min_pessoa_cot,
    t2.id AS mov_id,
    t2.nr_externo AS mov_nr_externo,
    t2.data_mov AS mov_data_mov,
    t2.numero_mov AS mov_numero_mov,
    t2.data_emissao AS mov_data_emissao,
    t2.serie_mov AS mov_serie_mov,
    t2.valor_total AS mov_valor_total,
    t2.observacao AS mov_obs,
    t2.tipo_frete AS mov_tipo_frete,
    fnstd('mov'::text, 'tipo_frete'::text, t2.tipo_frete::character varying::text) AS mov_tipo_frete_desc,
    t2.data_entrega AS mov_data_entrega,
    t2.data_entrada_saida AS mov_data_entrada_saida,
    t2.tipo_emissao_carga AS mov_tipo_emissao_carga,
    fnstd('mov'::text, 'tipo_emissao_carga'::text, t2.tipo_emissao_carga::character varying::text) AS mov_tipo_emissao_carga_desc,
    t2.tipo_modal_carga AS mov_tipo_modal_carga,
    t2.tipo_transportador_carga AS mov_tipo_transportador_carga,
    t2.valor_carga AS mov_valor_carga,
    t2.tipo_umedida_carga AS mov_tipo_umedida_carga,
    fnstd('mov'::text, 'tipo_umedida_carga'::text, t2.tipo_umedida_carga::text) AS mov_tipo_umedida_carga_desc,
    t2.qnt_carga AS mov_qnt_carga,
    t2.observacao_transp AS mov_obs_transp,
    t2.observacao_serv AS mov_obs_serv,
    t2.tipo_fretamento AS mov_tipo_fretamenti,
    t2.tipo_serv_frete AS mov_tipo_serv_frete,
    t2.tipo_tomador_serv_frete AS mov_tipo_tomador_serv_frete,
    t2.taf AS mov_taf,
    t2.data_anulacao AS mov_data_anulacao,
    t2.observacao_item AS mov_obs_item,
    t2.valor_financeiro_total AS mov_valor_financeiro_total,
    t2.valor_item_frete_total AS mov_valor_item_frete_total,
    t2.observacao_fiscal AS mov_obs_fiscal,
    t2.fis_tipo_resp_reten AS mov_fis_tipo_resp_reten,
    fnstd('mov'::text, 'fis_tipo_resp_reten'::text, t2.fis_tipo_resp_reten::text) AS mov_fis_tipo_resp_reten_desc,
    t2.fis_exig_iss_nfs AS mov_fis_exig_iss_nfs,
    fnstd('mov'::text, 'fis_exig_iss_nfs'::text, t2.fis_exig_iss_nfs::text) AS mov_fis_exig_iss_nfs_desc,
    t2.fis_iss_retido_nfs AS mov_fis_iss_retido_nfs,
    fnstd('SN'::text, 'default'::text, t2.fis_iss_retido_nfs::text) AS mov_fis_iss_retido_nfs_desc,
    t2.fis_nat_ope_nfs AS mov_fis_nat_ope_nfs,
    fnstd('mov'::text, 'fis_nat_ope_nfs'::text, t2.fis_nat_ope_nfs::text) AS mov_fis_nat_ope_nfs_desc,
    t2.numero_mov_pre AS mov_numero_mov_pre,
    t2.serio_mov_pre AS mov_serio_mov_pre,
    t2.cep_carreg AS mov_cep_carreg,
    t2.cep_descarreg AS mov_cep_descarreg,
    t2.tipo_carga AS mov_tipo_carga,
    fnstd('mov'::text, 'tipo_carga'::text, t2.tipo_carga::text) AS mov_tipo_carga_desc,
    t3.id AS ger_item_serv_id,
    t3.nome AS ger_item_serv_nome,
    t3.ativo AS ger_item_serv_ativo,
    fnstd('SN'::text, 'default'::text, t3.ativo::text) AS ger_item_serv_ativo_desc,
    t3.tipo AS ger_item_serv_tipo,
    fnstd('ger_itemserv'::text, 'tipo'::text, t3.tipo::text) AS ger_item_serv_tipo_desc,
    t3.sigla_itemserv AS ger_item_serv_sigla,
    t4.id AS ger_umedida_id,
    t4.nome AS ger_umedida_nome,
    t4.ativo AS ger_umedida_ativo,
    fnstd('SN'::text, 'default'::text, t4.ativo::text) AS ger_umedida_ativo_desc,
    t4.sigla_umedida AS ger_umedida_sigla,
    t4.nr_umedida AS ger_umedida_nr_umedida,
    t5.id AS fis_cfop_id,
    t5.nr_cfop AS fis_cfop_nr_cfop,
    t5.nome AS fis_cfop_nome,
    t5.ativo AS fis_cfop_ativo,
    fnstd('SN'::text, 'default'::text, t5.ativo::text) AS fis_cfop_ativo_desc,
    t5.data_validade AS fis_cfop_data_validade,
    t6.id AS ger_itemserv_lote_id,
    t6.nome AS ger_itemserv_lote_nome,
    t6.ativo AS ger_itemserv_lote_ativo,
    fnstd('SN'::text, 'default'::text, t6.ativo::text) AS ger_itemserv_lote_ativo_desc,
    t6.data_ini AS ger_itemserv_lote_data_ini,
    t6.data_fin AS ger_itemserv_lote_data_fin,
    t6.observacao AS ger_itemserv_lote_obs,
    t6.data_validade AS ger_itemserv_lote_data_validade,
    t7.id AS ger_itemserv_subgrupo_id,
    t7.nome AS ger_itemserv_subgrupo_nome,
    t7.ativo AS ger_itemserv_subgrupo_ativo,
    fnstd('SN'::text, 'default'::text, t7.ativo::text) AS ger_itemserv_subgrupo_ativo_desc,
    t8.id AS ger_itemserv_grupo_id,
    t8.nome AS ger_itemserv_grupo_nome,
    t8.ativo AS ger_itemserv_grupo_ativo,
    fnstd('SN'::text, 'default'::text, t8.ativo::text) AS ger_itemserv_grupo_ativo_desc,
    t1.log_user_ins,
    t1.log_date_ins,
    t1.log_user_upd,
    t1.log_date_upd,
    (t3.sigla_itemserv::text || ' - '::text) || t3.nome::text AS ger_item_serv_sigla_desc,
    (t4.sigla_umedida::text || ' - '::text) || t4.nome::text AS ger_umedida_sigla_desc,
    t2.mov_operacao_id as mov_operacao_id,
    t9.nome as mov_operacao_nome,
    t9.ativo as mov_operacao_ativo,
    t9.sigla_mov_operacao as mov_operacao_sigla_mov_operacao,
    t9.tipo_es as mov_operacao_tipo_es,
    t9.mov_tipo_id as mov_tipo_id,
    t10.nome as mov_tipo_nome,
    t10.ativo as mov_tipo_ativo,
    t10.sigla_mov_tipo as mov_tipo_sigla_mov_tipo,
    t10.tipo_mov as mov_tipo_tipo_mov
   FROM mov_itemserv t1
     JOIN mov t2 ON t1.mov_id::text = t2.id::text
     join mov_operacao t9 on t9.id::text = t2.mov_operacao_id::text
     join mov_tipo t10 on t10.id::text = t9.mov_tipo_id::text
     JOIN ger_itemserv t3 ON t1.ger_itemserv_id::text = t3.id::text
     JOIN ger_umedida t4 ON t1.ger_umedida_id_conv::text = t4.id::text
     LEFT JOIN fis_cfop t5 ON t1.fis_cfop_id::text = t5.id::text
     LEFT JOIN ger_itemserv_lote t6 ON t1.ger_itemserv_lote_id::text = t6.id::text
     JOIN ger_itemserv_subgrupo t7 ON t3.ger_itemserv_subgrupo_id::text = t7.id::text
     JOIN ger_itemserv_grupo t8 ON t7.ger_grupo_id::text = t8.id::text;