from alembic import op


revision = "202211100921001"
down_revision = "202211100921000"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
update sys_program set controller = '/private/ger/geritemserv' where controller like '%/itemserv';

insert into sys_action (id, name, code, active) values ('8a345fe2-84c4-417d-a0f4-f637db9f26a9', 'Add', 'ADD', 'S');

insert into sys_action (id, name, code, active) values ('373807e0-24c7-400e-ab89-2d986b0fb744', 'Add Det0', 'ADD_DET0', 'S');
insert into sys_action (id, name, code, active) values ('b908281f-e61f-43ad-b3c7-03db23f9ad34', 'Save Det0', 'SAVE_DET0', 'S');
insert into sys_action (id, name, code, active) values ('55a4e8a2-01e9-4be1-ac29-707558be498a', 'Edit Det0', 'EDIT_DET0', 'S');
insert into sys_action (id, name, code, active) values ('23e4b521-e663-417a-85c3-71f9c8893335', 'Delete Det0', 'DELETE_DET0', 'S');

insert into sys_action (id, name, code, active) values ('3d9aefa7-c08f-4ea2-971d-b607b00da318', 'Add Det0', 'ADD_DET1', 'S');
insert into sys_action (id, name, code, active) values ('e52ac69d-42b7-48e4-939c-0127e003f1db', 'Save Det1', 'SAVE_DET1', 'S');
insert into sys_action (id, name, code, active) values ('0dbe3ff9-ca59-44dd-b7ce-0f044943f035', 'Edit Det1', 'EDIT_DET1', 'S');
insert into sys_action (id, name, code, active) values ('78e32ee1-d2c9-433e-8ef7-5ed2578d8200', 'Delete Det1', 'DELETE_DET1', 'S');

insert into sys_action (id, name, code, active) values ('4be361f9-a7da-4c03-8c0c-d1fb084e1ac9', 'Add Det0', 'ADD_DET2', 'S');
insert into sys_action (id, name, code, active) values ('f5d74dfe-e7e3-4c52-a755-52afc5fd8df5', 'Save Det2', 'SAVE_DET2', 'S');
insert into sys_action (id, name, code, active) values ('5a7bdc29-0200-41e5-b532-05e12c5e925d', 'Edit Det2', 'EDIT_DET2', 'S');
insert into sys_action (id, name, code, active) values ('d1531e3c-71cf-467d-99e5-dc9521c4e448', 'Delete Det2', 'DELETE_DET2', 'S');

insert into sys_action (id, name, code, active) values ('079c657d-1cc8-4691-86a4-bb4f01b9fe04', 'Add Det0', 'ADD_DET3', 'S');
insert into sys_action (id, name, code, active) values ('0ef428e6-0154-4b78-a65b-2f85a45fbab2', 'Save Det3', 'SAVE_DET3', 'S');
insert into sys_action (id, name, code, active) values ('67c8f9b4-17d8-4b8d-9332-2598d04baceb', 'Edit Det3', 'EDIT_DET3', 'S');
insert into sys_action (id, name, code, active) values ('f938175e-5443-411d-af18-feff8ab1334a', 'Delete Det3', 'DELETE_DET3', 'S');

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('6421425c-3779-4438-be48-2caec4d7a506',(select id from sys_program where controller like '%/gercidade'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('c5a61199-c2b3-45b8-a9db-03c951a6bc8f',(select id from sys_program where controller like '%/gercidade'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('34b99c58-5b82-4812-b339-ce4cc4722341',(select id from sys_program where controller like '%/gercidade'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('5c6257ae-3c80-4be9-8305-296b198af06f',(select id from sys_program where controller like '%/gercidade'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gercidade') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gercidade') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gercidade') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gercidade') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('52c9b2d5-ad13-47b8-b8cd-f2315be93527',(select id from sys_program where controller like '%/gerdevice'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('b4f86a5a-9c38-4b3e-b1fb-273c069a5539',(select id from sys_program where controller like '%/gerdevice'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('52c15ff8-7aac-4cf9-afb2-0132ef2d66d3',(select id from sys_program where controller like '%/gerdevice'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('f1de8ba8-9888-4d03-95c2-bb17d95734b7',(select id from sys_program where controller like '%/gerdevice'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerdevice') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerdevice') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerdevice') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerdevice') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('8e5b9f9a-b725-4930-91d4-7fee9c6dca34',(select id from sys_program where controller like '%/gerempresa'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('6ec0e66e-c710-4f19-8825-b27ab444eeef',(select id from sys_program where controller like '%/gerempresa'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('ae6a3a6c-633e-4ad7-b028-468bb214aa30',(select id from sys_program where controller like '%/gerempresa'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('0cd2f439-fc9b-42fc-bdf6-230cc9648c76',(select id from sys_program where controller like '%/gerempresa'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresa') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresa') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresa') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresa') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('972c3654-2ee0-4586-a613-422b3199d4b0',(select id from sys_program where controller like '%/gerempresagrupo'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('2971d25f-06fe-4ae1-b690-3f0345999da1',(select id from sys_program where controller like '%/gerempresagrupo'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('dbe7eebd-d64f-4137-a641-707469c87015',(select id from sys_program where controller like '%/gerempresagrupo'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('2417ddc0-6e04-4074-acf4-b8ababc864ee',(select id from sys_program where controller like '%/gerempresagrupo'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresagrupo') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresagrupo') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresagrupo') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresagrupo') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('5da6348a-c4e1-4b47-82b2-dc47b90a1f78',(select id from sys_program where controller like '%/gerestnivel'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('02beb6ab-e2ca-4d6c-b974-c77963ab09c6',(select id from sys_program where controller like '%/gerestnivel'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('37430aee-91ab-455c-a863-a583b07d9ec6',(select id from sys_program where controller like '%/gerestnivel'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('676f97d0-2cee-459d-817a-c21eb39a179b',(select id from sys_program where controller like '%/gerestnivel'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerestnivel') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerestnivel') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerestnivel') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerestnivel') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('f44d047b-e665-4a78-a5cc-964a755955b2',(select id from sys_program where controller like '%/gerindex'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('c1d20522-b41c-4a61-8166-74d0a4a8e842',(select id from sys_program where controller like '%/gerindex'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('1eac8292-fa66-41ee-83b8-a2aa5be0dcf0',(select id from sys_program where controller like '%/gerindex'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('18296cee-6e62-457d-9c62-3303e2ca6d81',(select id from sys_program where controller like '%/gerindex'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerindex') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerindex') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerindex') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerindex') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('4378bfb6-d90a-45c1-bb11-ad86a606adc6',(select id from sys_program where controller like '%/geritemservcompostipo'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('eef33d34-a8a6-44b0-92b8-50dbcc125285',(select id from sys_program where controller like '%/geritemservcompostipo'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('6c6ef14e-5917-48f6-b794-6c812f19cc8f',(select id from sys_program where controller like '%/geritemservcompostipo'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('d9890425-cb2d-4122-a03f-15bc1e3e6872',(select id from sys_program where controller like '%/geritemservcompostipo'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservcompostipo') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservcompostipo') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservcompostipo') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservcompostipo') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('563ad9ed-2365-47d2-be02-8c672b42a387',(select id from sys_program where controller like '%/geritemservgrupo'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('f1bccafa-50d9-41a4-8f4a-4006a99190e8',(select id from sys_program where controller like '%/geritemservgrupo'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('67574d91-47bd-425c-b5b3-ea58e9e79435',(select id from sys_program where controller like '%/geritemservgrupo'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('50a439d3-26e9-4cad-9892-7621b6d4e790',(select id from sys_program where controller like '%/geritemservgrupo'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservgrupo') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservgrupo') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservgrupo') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservgrupo') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('a6fe4977-7bf3-4885-a331-ba288f28feb9',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('74077ac1-1249-4919-80a0-c605c63698e0',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('78107244-8a5b-4b01-bc3e-896a4cfd80c1',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('423fd315-881d-4816-8c68-813f5770795f',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('401935fe-e09d-48da-8c67-21c01999d0df',(select id from sys_program where controller like '%/gernumeracao'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('c23240de-bb73-431d-959c-eb8a4dc8834a',(select id from sys_program where controller like '%/gernumeracao'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('01c1070c-3104-4378-9f95-42d0718d11d6',(select id from sys_program where controller like '%/gernumeracao'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('58e329c4-b9dc-4fc1-aace-e36356d6ce49',(select id from sys_program where controller like '%/gernumeracao'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gernumeracao') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gernumeracao') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gernumeracao') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gernumeracao') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('34d7aee7-0d1a-4a82-b2e1-4d550d39d600',(select id from sys_program where controller like '%/gerpais'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('b3f77aa4-e081-41c1-9759-e919a8a89e51',(select id from sys_program where controller like '%/gerpais'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('69f5acd6-14fe-4a45-9f4b-5a74ba63c49e',(select id from sys_program where controller like '%/gerpais'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('a9a18fdb-909b-4a2b-88de-e6fd5a6ffa8a',(select id from sys_program where controller like '%/gerpais'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpais') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpais') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpais') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpais') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('5abb7b2c-f764-4c49-9b73-c1315f51b260',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('2084b4a9-e6b4-4503-8937-39eb31d476d4',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('64313f0e-23a0-478f-b26e-88a12640134e',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('659964ab-4a67-433e-b307-ea7e10946233',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('daf72685-eb76-426a-919b-b6b0c56c6c92',(select id from sys_program where controller like '%/gerumedida'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('4db90171-b763-4778-ad33-5a550f750fca',(select id from sys_program where controller like '%/gerumedida'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('838ccd33-64ae-4ce0-bcb5-bbec42864e13',(select id from sys_program where controller like '%/gerumedida'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('846b891d-100a-40c7-bbd7-d95c58ff327a',(select id from sys_program where controller like '%/gerumedida'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerumedida') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerumedida') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerumedida') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerumedida') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('c0f5ffb6-9a01-4e68-a669-4849f30c15d4',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('6193c2ae-9a75-4d03-aab4-aa72e1109e4b',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('705ec60c-a389-49f8-a9a5-eadebc74572a',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('16a2e5c4-70ba-4a57-a630-9a95103bfba7',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('534c3586-0485-4a86-b490-a6df627f1044',(select id from sys_program where controller like '%/gerunitparam'),(select id from sys_action sa  where code = 'ADD'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('16bcd0df-774a-45a7-9a6f-c05bc3012666',(select id from sys_program where controller like '%/gerunitparam'),(select id from sys_action sa  where code = 'EDIT'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('792f25ca-b2e9-4ae1-9478-c9921d00d842',(select id from sys_program where controller like '%/gerunitparam'),(select id from sys_action sa  where code = 'DELETE'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('cd1ecefc-c1ef-40fa-b8ea-ce66e3de4aed',(select id from sys_program where controller like '%/gerunitparam'),(select id from sys_action sa  where code = 'SAVE'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerunitparam') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerunitparam') and sys_action_id = (select id from sys_action sa  where code = 'EDIT')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerunitparam') and sys_action_id = (select id from sys_action sa  where code = 'DELETE')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerunitparam') and sys_action_id = (select id from sys_action sa  where code = 'SAVE')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('8e722469-59a3-4c3f-be95-9a65d1035ace',(select id from sys_program where controller like '%/test1'),(select id from sys_action sa  where code = 'ADD'));

insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/test1') and sys_action_id = (select id from sys_action sa  where code = 'ADD')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('94973e1b-87b4-4879-9b90-10e2eb3b178c',(select id from sys_program where controller like '%/test1'),(select id from sys_action sa  where code = 'SAVE_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('2616ae0a-97c8-4809-8745-9a5eb7559138',(select id from sys_program where controller like '%/test1'),(select id from sys_action sa  where code = 'ADD_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('53dc17a2-8505-494c-88f6-5be80c6f5447',(select id from sys_program where controller like '%/test1'),(select id from sys_action sa  where code = 'EDIT_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('46af1955-fb85-4c36-af77-7267837216c9',(select id from sys_program where controller like '%/test1'),(select id from sys_action sa  where code = 'DELETE_DET0'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/test1') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/test1') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/test1') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/test1') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET0')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('57fee08c-4c5e-4f10-a9da-626437822e0a',(select id from sys_program where controller like '%/gerdevice'),(select id from sys_action sa  where code = 'SAVE_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('96115346-c8ae-4ccf-bc81-a9cac11edaef',(select id from sys_program where controller like '%/gerdevice'),(select id from sys_action sa  where code = 'ADD_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('f3b57bd9-be34-4dea-b594-c2afcfff0d58',(select id from sys_program where controller like '%/gerdevice'),(select id from sys_action sa  where code = 'EDIT_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('20dbcac1-78aa-40f9-8d2f-6ed0cf4af163',(select id from sys_program where controller like '%/gerdevice'),(select id from sys_action sa  where code = 'DELETE_DET0'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerdevice') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerdevice') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerdevice') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerdevice') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET0')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('d184745d-c5ad-4152-9484-f50753cccad7',(select id from sys_program where controller like '%/gerempresa'),(select id from sys_action sa  where code = 'SAVE_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('81b4b7ed-baf3-4dd8-99df-803638e04841',(select id from sys_program where controller like '%/gerempresa'),(select id from sys_action sa  where code = 'ADD_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('f3c62095-6c6e-47f6-b753-72f78a826a7c',(select id from sys_program where controller like '%/gerempresa'),(select id from sys_action sa  where code = 'EDIT_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('5ad5a1d9-4823-4032-a2a1-24948985e487',(select id from sys_program where controller like '%/gerempresa'),(select id from sys_action sa  where code = 'DELETE_DET0'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresa') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresa') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresa') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerempresa') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET0')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('565718cf-dcba-441f-92f4-683d10aa0267',(select id from sys_program where controller like '%/geritemservgrupo'),(select id from sys_action sa  where code = 'SAVE_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('2b9db008-cd17-499c-a4aa-c3c459605537',(select id from sys_program where controller like '%/geritemservgrupo'),(select id from sys_action sa  where code = 'ADD_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('651a80a6-9214-4b27-b5f1-d497a2ab7ff4',(select id from sys_program where controller like '%/geritemservgrupo'),(select id from sys_action sa  where code = 'EDIT_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('8fc5aa91-52ee-4e46-b9e7-b445fde6ddd8',(select id from sys_program where controller like '%/geritemservgrupo'),(select id from sys_action sa  where code = 'DELETE_DET0'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservgrupo') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservgrupo') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservgrupo') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemservgrupo') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET0')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('7d4ed75d-631a-4b58-a440-f915bcf4b41d',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'SAVE_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('d371c8ec-ea0a-492f-9854-aad2323a264e',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'ADD_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('9e9e5bdd-eadb-4500-a6f2-286c499de6fd',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'EDIT_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('cfaf3cc4-6123-4b45-84d1-326889665d39',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'DELETE_DET0'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET0')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('5f26433e-e340-4315-b8ce-0bb3092c9a95',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'SAVE_DET1'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('35ea3834-551d-4467-82df-e108a0e2038e',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'ADD_DET1'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('31716dc0-8832-46fa-981f-9cc3446698f8',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'EDIT_DET1'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('c85970b7-311c-4630-974f-9ba5ee32485f',(select id from sys_program where controller like '%/germarca'),(select id from sys_action sa  where code = 'DELETE_DET1'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET1')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET1')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET1')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/germarca') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET1')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('03c6950c-392a-40e3-b2b5-a3c6c5327eb8',(select id from sys_program where controller like '%/gerpais'),(select id from sys_action sa  where code = 'SAVE_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('fdb8ba77-1157-44b1-893d-13db744007af',(select id from sys_program where controller like '%/gerpais'),(select id from sys_action sa  where code = 'ADD_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('1383ef0f-302f-4bb4-913c-c76349b6dcd7',(select id from sys_program where controller like '%/gerpais'),(select id from sys_action sa  where code = 'EDIT_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('de624d17-821f-486a-b9f6-3e7bcf0d2155',(select id from sys_program where controller like '%/gerpais'),(select id from sys_action sa  where code = 'DELETE_DET0'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpais') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpais') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpais') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpais') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET0')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('70c627ab-5da7-4f7b-8950-5077dd68c760',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'SAVE_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('66be3d30-72c9-4c12-8e87-fe3feb707241',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'ADD_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('50bf801c-fd99-45d1-8bfb-5a0bcde85e76',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'EDIT_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('1c7f0b5e-ded2-41a3-908a-b4cf8068c3f8',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'DELETE_DET0'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET0')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('35786ed6-89e2-4e1b-9d2a-07e3fce49b84',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'SAVE_DET1'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('348ae85f-8c62-4456-9656-908516eb5bf0',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'ADD_DET1'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('8d13f7dd-f756-42a6-86c6-01f3ab2d20f4',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'EDIT_DET1'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('ecdf373f-1ff4-4afa-a6a3-0f7cbbc6f5ce',(select id from sys_program where controller like '%/gerpessoa'),(select id from sys_action sa  where code = 'DELETE_DET1'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET1')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET1')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET1')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerpessoa') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET1')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('99274c01-b632-4ae3-8356-e1895485e7b8',(select id from sys_program where controller like '%/gerumedida'),(select id from sys_action sa  where code = 'SAVE_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('ad4e25b5-592f-4658-85c2-e199f7fc3447',(select id from sys_program where controller like '%/gerumedida'),(select id from sys_action sa  where code = 'ADD_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('d2164451-bd17-4f4d-bfc5-b2419ca5c00c',(select id from sys_program where controller like '%/gerumedida'),(select id from sys_action sa  where code = 'EDIT_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('bb0edae9-886d-4b86-b152-88fb17086d3c',(select id from sys_program where controller like '%/gerumedida'),(select id from sys_action sa  where code = 'DELETE_DET0'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerumedida') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerumedida') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerumedida') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/gerumedida') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET0')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('44afb51c-3d6b-4e78-9c97-3fabe56997b9',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'SAVE_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('887454ef-30dd-4542-a967-8178cac00c21',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'ADD_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('cb8c4c8e-ddb8-46f5-8cb2-5ffff12fc7b6',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'EDIT_DET0'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('e1cfce4a-1c57-487a-9e12-850996103c98',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'DELETE_DET0'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET0')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET0')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('0ab78255-8883-421b-85d9-15af3a2ceaf6',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'SAVE_DET1'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('440f3c03-5070-4667-838c-70e54fc698b8',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'ADD_DET1'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('93203560-be29-44cd-8f8f-a77516d8ca20',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'EDIT_DET1'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('bbb8061e-4c96-4cef-8603-428c9e7e78c1',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'DELETE_DET1'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET1')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET1')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET1')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET1')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('683bd0d9-cc8c-45c8-b7c9-87b3b286ef70',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'SAVE_DET2'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('766e54ab-e6a9-476e-b45f-828ecb1ff0df',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'ADD_DET2'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('f41a0f20-0140-43d6-ba50-2c18cb43405b',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'EDIT_DET2'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('a7727ce8-934a-4376-a190-d42347ce8b9a',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'DELETE_DET2'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET2')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET2')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET2')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET2')));

insert into sys_program_action (id, sys_program_id, sys_action_id) values ('55a4e9ed-f21d-4409-b00c-f715a9dbb1ba',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'SAVE_DET3'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('645fe0ca-748e-46c7-a87b-13935d5e62b8',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'ADD_DET3'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('f348dcd4-05f0-446c-84da-95e43a487a66',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'EDIT_DET3'));
insert into sys_program_action (id, sys_program_id, sys_action_id) values ('f9ba6c13-653d-4183-a69a-6ac269b5a438',(select id from sys_program where controller like '%/geritemserv'),(select id from sys_action sa  where code = 'DELETE_DET3'));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'SAVE_DET3')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'ADD_DET3')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'EDIT_DET3')));
insert into sys_group_program_action (sys_group_id, sys_program_action_id) values ('4218d8f1-8595-4052-aace-ba36f772623e', (select id from sys_program_action where sys_program_id = (select id from sys_program where controller like '%/geritemserv') and sys_action_id = (select id from sys_action sa  where code = 'DELETE_DET3')));

ALTER TABLE test1 ALTER COLUMN hr_nascimento TYPE timestamp USING hr_nascimento::timestamp;

alter table sys_user_preference add object_sub_id varchar(36);
COMMENT ON COLUMN sys_user_preference.object_sub_id IS 'ID do Objeto-Sub';

alter table sys_user_preference add ispublic varchar(1);
COMMENT ON COLUMN sys_user_preference.ispublic IS 'Publico';

--================================================================
--Liberar acesso para todos usuários
--================================================================
--admin interno
delete from sys_group_program a where sys_group_id='4218d8f1-8595-4052-aace-ba36f772623e';
insert into sys_group_program(id,sys_group_id,sys_program_id)
select uuid_generate_v4(),'4218d8f1-8595-4052-aace-ba36f772623e', b.id
from sys_program b;
--admin unit
delete from sys_group_program a where sys_group_id='0256e515-51a4-49a2-a8b8-adc36470cd51';
insert into sys_group_program(id,sys_group_id,sys_program_id)
select uuid_generate_v4(),'0256e515-51a4-49a2-a8b8-adc36470cd51', b.id
from sys_program b where b.admin='N';
commit;
--actions
delete from sys_group_program_action a where sys_group_id in('4218d8f1-8595-4052-aace-ba36f772623e','0256e515-51a4-49a2-a8b8-adc36470cd51');
--actions - interno
insert into sys_group_program_action(id,sys_group_id,sys_program_action_id)
select uuid_generate_v4(),'4218d8f1-8595-4052-aace-ba36f772623e', c.id
from sys_program b 
join sys_program_action c on(b.id = c.sys_program_id);
commit;
--actions - unit
insert into sys_group_program_action(id,sys_group_id,sys_program_action_id)
select uuid_generate_v4(),'0256e515-51a4-49a2-a8b8-adc36470cd51', c.id
from sys_program b 
join sys_program_action c on(b.id = c.sys_program_id) where b.admin='N';
commit;
"""
    )


def downgrade():
    pass
