CREATE OR REPLACE VIEW vwind AS
select 
t1.unit_id,
t1.id,
t1.sigla_ind as ind_sigla_ind,
t1.nome as ind_nome,
t1.casas_dec as ind_casas_dec,
t1.campo_ordenacao as ind_campo_ordenacao,
t1.metodo_ordenacao as ind_metodo_ordenacao,
fnstd('ind' ,'metodo_ordenacao',(t1.metodo_ordenacao)::TEXT) as ind_metodo_ordenacao_desc,
t1.totalizador_atributo as ind_totalizador_atributo,
fnstd('ind' ,'totalizador_atributo',(t1.totalizador_atributo)::TEXT) as ind_totalizador_atributo_desc,
t1.exibir_media_real as ind_exibir_media_real,
fnstd('SN','default',t1.exibir_media_real) as ind_exibir_media_real_desc,
t1.exibir_media_meta as ind_exibir_media_meta,
fnstd('SN','default',t1.exibir_media_meta) as ind_exibir_media_meta_desc,
t1.exibir_dia as ind_exibir_dia,
fnstd('SN','default',t1.exibir_dia) as ind_exibir_dia_desc,
t1.exibir_semana as ind_exibir_semana,
fnstd('SN','default',t1.exibir_semana) as ind_exibir_semana_desc,
t1.exibir_quinzena as ind_exibir_quinzena,
fnstd('SN','default',t1.exibir_quinzena) as ind_exibir_quinzena_desc,
t1.exibir_mes as ind_exibir_mes,
fnstd('SN','default',t1.exibir_mes) as ind_exibir_mes_desc,
t1.exibir_bimestre as ind_exibir_bimestre,
fnstd('SN','default',t1.exibir_bimestre) as ind_exibir_bimestre_desc,
t1.exibir_trimestre as ind_exibir_trimestre,
fnstd('SN','default',t1.exibir_trimestre) as ind_exibir_trimestre_desc,
t1.exibir_quadrimestre as ind_exibir_quadrimestre,
fnstd('SN','default',t1.exibir_quadrimestre) as ind_exibir_quadrimestre_desc,
t1.exibir_semestre as ind_exibir_semestre,
fnstd('SN','default',t1.exibir_semestre) as ind_exibir_semestre_desc,
t1.exibir_ano as ind_exibir_ano,
fnstd('SN','default',t1.exibir_ano) as ind_exibir_ano_desc,
t1.acumular_semana as ind_acumular_semana,
fnstd('SN','default',t1.acumular_semana) as ind_acumular_semana_desc,
t1.acumular_quinzena as ind_acumular_quinzena,
fnstd('SN','default',t1.acumular_quinzena) as ind_acumular_quinzena_desc,
t1.acumular_mes as ind_acumular_mes,
fnstd('SN','default',t1.acumular_mes) as ind_acumular_mes_desc,
t1.acumular_bimestre as ind_acumular_bimestre,
fnstd('SN','default',t1.acumular_bimestre) as ind_acumular_bimestre_desc,
t1.acumular_trimestre as ind_acumular_trimestre,
fnstd('SN','default',t1.acumular_trimestre) as ind_acumular_trimestre_desc,
t1.acumular_quadrimestre as ind_acumular_quadrimestre,
fnstd('SN','default',t1.acumular_quadrimestre) as ind_acumular_quadrimestre_desc,
t1.acumular_semestre as ind_acumular_semestre,
fnstd('SN','default',t1.acumular_semestre) as ind_acumular_semestre_desc,
t1.acumular_ano as ind_acumular_ano,
fnstd('SN','default',t1.acumular_ano) as ind_acumular_ano_desc,
t1.tipo_acumulo as ind_tipo_acumulo,
fnstd('ind' ,'tipo_acumulo',(t1.tipo_acumulo)::TEXT) as ind_tipo_acumulo_desc, 
t1.ind_id_ponderacao as ind_ind_id_ponderacao,
t1.grafico_tipo_atributo as ind_grafico_tipo_atributo,
fnstd('ind' ,'grafico_tipo_atributo',(t1.grafico_tipo_atributo)::TEXT) as ind_grafico_tipo_atributo_desc, 
t1.grafico_valor_vazio_zero as ind_grafico_valor_vazio_zero,
t1.grafico_tipo_ind as ind_grafico_tipo_ind,
fnstd('ind' ,'grafico_tipo_ind',(t1.grafico_tipo_ind)::TEXT) as ind_grafico_tipo_ind_desc,  
t1.ger_umedida_id as ind_ger_umedida_id,
t1.log_user_ins,
t1.log_date_ins,
t1.log_user_upd,
t1.log_date_upd,
t1.tipo_meta as ind_tipo_meta,
fnstd('ind' ,'tipo_meta',(t1.tipo_meta)::TEXT) as ind_tipo_meta_desc,  
t1.faixa_meta_vr_01 as ind_faixa_meta_vr_01,
t1.faixa_meta_vr_02 as ind_faixa_meta_vr_02,
t1.faixa_meta_vr_03 as ind_faixa_meta_vr_03,
t1.faixa_meta_vr_04 as ind_faixa_meta_vr_04,
t1.faixa_meta_vr_05 as ind_faixa_meta_vr_05,
t1.faixa_meta_cor_01 as ind_faixa_meta_cor_01,
t1.faixa_meta_cor_02 as ind_faixa_meta_cor_02,
t1.faixa_meta_cor_03 as ind_faixa_meta_cor_03,
t1.faixa_meta_cor_04 as ind_faixa_meta_cor_04,
t1.faixa_meta_cor_05 as ind_faixa_meta_cor_05,
t1.ativo as ind_ativo,
fnstd('SN','default',t1.ativo) as ind_ativo_desc,
t1.observacao as ind_observacao,
t1.qnt_dia_hist_ant as ind_qnt_dia_hist_ant,
t1.qnt_dia_hist_prox as ind_qnt_dia_hist_prox,
t1.qnt_semana_hist_ant as ind_qnt_semana_hist_ant,
t1.qnt_semana_hist_prox as ind_qnt_semana_hist_prox,
t1.qnt_quinzena_hist_ant as ind_qnt_quinzena_hist_ant,
t1.qnt_quinzena_hist_prox as ind_qnt_quinzena_hist_prox,
t1.qnt_mes_hist_ant as ind_qnt_mes_hist_ant,
t1.qnt_mes_hist_prox as ind_qnt_mes_hist_prox,
t1.qnt_bimestre_hist_ant as ind_qnt_bimestre_hist_ant,
t1.qnt_bimestre_hist_prox as ind_qnt_bimestre_hist_prox,
t1.qnt_trimestre_hist_ant as ind_qnt_trimestre_hist_ant,
t1.qnt_trimestre_hist_prox as ind_qnt_trimestre_hist_prox,
t1.qnt_quadrimestre_hist_ant as ind_qnt_quadrimestre_hist_ant,
t1.qnt_quadrimestre_hist_prox as ind_qnt_quadrimestre_hist_prox,
t1.qnt_semestre_hist_ant as ind_qnt_semestre_hist_ant,
t1.qnt_semestre_hist_prox as ind_qnt_semestre_hist_prox,
t1.qnt_ano_hist_ant as ind_qnt_ano_hist_ant,
t1.qnt_ano_hist_prox as ind_qnt_ano_hist_prox,
t2.sigla_ind as ind_sigla_ind_ponderacao,
t2.nome as ind_nome_ponderacao
from ind t1
left join ind t2 on(t1.ind_id_ponderacao = t2.id);