CREATE OR REPLACE VIEW public.vwope_centro2_area AS
SELECT
    c.unit_id,
    c.unit_id AS ope_centro2_area_unit_id,
    c.id AS ope_centro2_area_id,
    c.qnt_area_prod AS ope_centro2_area_qnt_area_prod,
    c.qnt_area_improd AS ope_centro2_area_qnt_area_improd,
    c.qnt_plantas_estande AS ope_centro2_area_qnt_plantas_estande,
    c.bloco_col AS ope_centro2_area_bloco_col,
    c.lat_x AS ope_centro2_area_lat_x,
    c.long_y AS ope_centro2_area_long_y,
    c.alt_z AS ope_centro2_area_alt_z,
    c.data_ini_plan AS ope_centro2_area_data_ini_plan,
    c.data_fin_plan AS ope_centro2_area_data_fin_plan,
    c.data_ult_plan AS ope_centro2_area_data_ult_plan,
    c.data_ini_col AS ope_centro2_area_data_ini_col,
    c.data_fin_col AS ope_centro2_area_data_fin_col,
    c.data_ult_col AS ope_centro2_area_data_ult_col,
    c.data_florada_1 AS ope_centro2_area_data_florada_1,
    c.data_emerg AS ope_centro2_area_data_emerg,
    c.observacao AS ope_centro2_area_observacao,
    i.id AS ope_centro2_area_umedida_id,
    i.nome AS ope_centro2_area_umedida_nome,
    i.sigla_umedida AS ope_centro2_area_umedida_sigla,
    j.id AS ope_tipo_solo_id,
    j.nome AS ope_centro2_area_tipo_solo_nome,
    j.sigla_tipo_solo AS ope_centro2_area_tipo_solo_sigla,
    k.id AS ope_centro2_area_espacamento_id,
    k.nome AS ope_centro2_area_espacamento_nome,
    k.sigla_espac AS ope_centro2_area_espacamento_sigla,
    l.id AS ope_centro2_area_atividade_sistema_cult_id,
    l.nome AS ope_centro2_area_atividade_sistema_cult_nome,
    l.sigla_atividade_grupo AS ope_centro2_area_atividade_sistema_cult_sigla,
    q.id AS ope_centro2_area_atividade_sistema_plan_id,
    q.nome AS ope_centro2_area_atividade_sistema_plan_nome,
    q.sigla_atividade_grupo AS ope_centro2_area_atividade_sistema_plan_sigla,
    r.id AS ope_centro2_area_atividade_sistema_col_id,
    r.nome AS ope_centro2_area_atividade_sistema_col_nome,
    r.sigla_atividade_grupo AS ope_centro2_area_atividade_sistema_col_sigla,
    m.id AS ope_centro2_area_item_serv_id,
    m.nome AS ope_centro2_area_item_serv_nome,
    m.sigla_itemserv AS ope_centro2_area_item_serv_sigla,
    m.ativo AS ope_centro2_area_item_serv_ativo,
    fnstd ('SN'::text, 'default'::text, m.ativo::text) AS ope_centro2_area_item_serv_ativo_desc,
    s.nome AS ope_centro2_area_item_serv_umedida_nome,
    s.sigla_umedida AS ope_centro2_area_item_serv_umedida_sigla,
    n.nome AS ope_centro2_area_item_serv_var_nome,
    n.sigla_itemserv AS ope_centro2_area_item_serv_var_sigla,
    o.nome AS ope_centro2_area_item_serv_ultimo_nome,
    o.sigla_itemserv AS ope_centro2_area_item_serv_ultimo_sigla,
    p.nome AS ope_centro2_area_item_serv_var_ultimo_nome,
    p.sigla_itemserv AS ope_centro2_area_item_serv_var_ultimo_sigla,
    a.unit_id AS ope_centro1_unit_id,
    a.id AS ope_centro1_id,
    a.sigla_centro1 AS ope_centro1_sigla,
    a.nome AS ope_centro1_nome,
    a.observacao AS ope_centro1_observacao,
    a.ativo AS ope_centro1_ativo,
    fnstd ('SN'::text, 'default'::text, a.ativo::text) AS ope_centro1_ativo_desc,
    u.id AS ope_centro1_pessoa_id,
    u.nome AS ope_centro1_pessoa_nome,
    u.sigla_pes AS ope_centro1_pessoa_sigla,
    u.doc_cpf AS ope_centro1_pessoa_doc_cpf,
    u.doc_cnpj AS ope_centro1_pessoa_doc_cpnj,
    fnutil_formatcpfcnpj (u.id, FALSE) AS ope_centro1_pessoa_doc_cpf_cpnj_desc,
    b.id AS ope_centro2_id,
    b.sigla_centro2 AS ope_centro2_sigla,
    b.nome AS ope_centro2_nome,
    b.ativo AS ope_centro2_ativo,
    fnstd ('SN'::text, 'default'::text, b.ativo::text) AS ope_centro2_ativo_desc,
    b.tipo_destinacao AS ope_centro2_tipo_destinacao,
    fnstd ('ope_centro2'::text, 'tipo_destinacao'::text, b.tipo_destinacao::text) AS ope_centro2_tipo_destinacao_desc,
    b.tipo_prop AS ope_centro2_tipo_prop,
    fnstd ('ope_centro2'::text, 'tipo_prop'::text, b.tipo_prop::text) AS ope_centro2_tipo_prop_desc,
    t.id AS ope_centro_rat_tipo_id,
    t.nome AS ope_centro_rat_tipo_nome,
    t.sigla_centro_rat_tipo AS ope_centro_rat_tipo_sigla,
    t.ativo AS ope_centro_rat_tipo_ativo,
    fnstd ('SN'::text, 'default'::text, t.ativo::text) AS ope_centro_rat_tipo_ativo_desc,
    d.id AS ope_centro_subtipo_id,
    d.nome AS ope_centro_subtipo_nome,
    e.id AS ope_centro_tipo_id,
    e.nome AS ope_centro_tipo_nome,
    e.tipo_es AS ope_centro_tipo_es,
    fnstd ('default'::text, 'tipo_es'::text, e.tipo_es::text) AS ope_centro_tipo_es_desc,
    f.id AS ope_centro_subgrupo_id,
    f.nome AS ope_centro_subgrupo_nome,
    f.sigla_centro_subgrupo AS ope_centro_subgrupo_sigla,
    f.ativo AS ope_centro_subgrupo_ativo,
    fnstd ('SN'::text, 'default'::text, f.ativo::text) AS ope_centro_subgrupo_ativo_desc,
    g.id AS ope_centro_grupo_id,
    g.nome AS ope_centro_grupo_nome,
    g.sigla_centro_grupo AS ope_centro_grupo_sigla,
    g.ativo AS ope_centro_grupo_ativo,
    fnstd ('SN'::text, 'default'::text, g.ativo::text) AS ope_centro_grupo_ativo_desc,
    h.id AS ope_periodo_id,
    h.nome AS ope_periodo_nome,
    h.sigla_periodo AS ope_periodo_sigla,
    h.ativo AS ope_periodo_ativo,
    fnstd ('SN'::text, 'default'::text, h.ativo::text) AS ope_periodo_ativo_desc,
    h.data_ini AS ope_periodo_data_ini,
    h.data_fin AS ope_periodo_data_fin,
    c.log_user_ins,
    c.log_date_ins,
    c.log_user_upd,
    c.log_date_upd,
    (i.sigla_umedida::text || ' - '::text) || i.nome::text AS ope_centro2_area_umedida_sigla_desc,
    (j.sigla_tipo_solo::text || ' - '::text) || j.nome::text AS ope_centro2_area_tipo_solo_sigla_desc,
    (k.sigla_espac::text || ' - '::text) || k.nome::text AS ope_centro2_area_espacamento_sigla_desc,
    (l.sigla_atividade_grupo::text || ' - '::text) || l.nome::text AS ope_centro2_area_atividade_sistema_cult_sigla_desc,
    (q.sigla_atividade_grupo::text || ' - '::text) || q.nome::text AS ope_centro2_area_atividade_sistema_plan_sigla_desc,
    (r.sigla_atividade_grupo::text || ' - '::text) || r.nome::text AS ope_centro2_area_atividade_sistema_col_sigla_desc,
    (m.sigla_itemserv::text || ' - '::text) || m.nome::text AS ope_centro2_area_item_serv_sigla_desc,
    (s.sigla_umedida::text || ' - '::text) || s.nome::text AS ope_centro2_area_item_serv_umedida_sigla_desc,
    (n.sigla_itemserv::text || ' - '::text) || n.nome::text AS ope_centro2_area_item_serv_var_sigla_desc,
    (o.sigla_itemserv::text || ' - '::text) || o.nome::text AS ope_centro2_area_item_serv_ultimo_sigla_desc,
    (p.sigla_itemserv::text || ' - '::text) || p.nome::text AS ope_centro2_area_item_serv_var_ultimo_sigla_desc,
    (a.sigla_centro1::text || ' - '::text) || a.nome::text AS ope_centro1_sigla_desc,
    (u.sigla_pes::text || ' - '::text) || u.nome::text AS ope_centro1_pessoa_sigla_desc,
    (b.sigla_centro2::text || ' - '::text) || b.nome::text AS ope_centro2_sigla_desc,
    (t.sigla_centro_rat_tipo::text || ' - '::text) || t.nome::text AS ope_centro_rat_tipo_sigla_desc,
    (f.sigla_centro_subgrupo::text || ' - '::text) || f.nome::text AS ope_centro_subgrupo_sigla_desc,
    (g.sigla_centro_grupo::text || ' - '::text) || g.nome::text AS ope_centro_grupo_sigla_desc,
    (h.sigla_periodo::text || ' - '::text) || h.nome::text AS ope_periodo_sigla_desc,
	b.tipo_ctb_comp as ope_centro2_tipo_ctb_comp,
	fnstd('ope_centro2'::text,
	'tipo_ctb_comp'::text,
	b.tipo_ctb_comp::text) as ope_centro2_tipo_ctb_comp_desc,
	b.ctb_comp_id as ope_centro2_ctb_comp_id,
	ccomp.nome as ope_centro2_ctb_comp_nome,
    ccomp.sigla_comp as ope_centro2_ctb_comp_sigla,
	(ccomp.sigla_comp || ' - ') || ccomp.nome as ope_centro2_ctb_comp_sigla_desc,
    ccomp.ativo as ope_centro2_ctb_comp_ativo
FROM
    ope_centro2_area c
    JOIN ope_centro2 b ON c.ope_centro2_id::text = b.id::text
    LEFT JOIN ope_centro_rat_tipo t ON b.ope_centro_rat_tipo_id::text = t.id::text
    JOIN ope_centro1 a ON b.ope_centro1_id::text = a.id::text
    LEFT JOIN ger_pessoa u ON a.ger_pessoa_id::text = u.id::text
    JOIN ope_centro_subtipo d ON a.ope_centro_subtipo_id::text = d.id::text
    JOIN ope_centro_tipo e ON d.ope_centro_tipo_id::text = e.id::text
    LEFT JOIN ope_centro_subgrupo f ON b.ope_centro_subgrupo_id::text = f.id::text
    LEFT JOIN ope_centro_grupo g ON f.ope_centro_grupo_id::text = g.id::text
    LEFT JOIN ope_periodo h ON c.ope_periodo_id::text = h.id::text
    LEFT JOIN ger_umedida i ON c.ger_umedida_id::text = i.id::text
    LEFT JOIN ope_tipo_solo j ON c.ope_tipo_solo_id::text = j.id::text
    LEFT JOIN ope_espac k ON c.ope_espac_id::text = k.id::text
    LEFT JOIN ope_atividade_sistema l ON c.ope_atividade_sistema_id_cult::text = l.id::text
    LEFT JOIN ope_atividade_sistema q ON c.ope_atividade_sistema_id_plan::text = q.id::text
    LEFT JOIN ope_atividade_sistema r ON c.ope_atividade_sistema_id_col::text = r.id::text
    LEFT JOIN ger_itemserv m ON c.ger_itemserv_id::text = m.id::text
    LEFT JOIN ger_umedida s ON m.ger_umedida_id::text = s.id::text
    LEFT JOIN ger_itemserv n ON c.ger_itemserv_var_id::text = n.id::text
    LEFT JOIN ger_itemserv o ON c.ger_itemserv_id_ult::text = o.id::text
    LEFT JOIN ger_itemserv p ON c.ger_itemserv_var_id_ult::text = p.id::text
	left join ctb_comp ccomp on b.ctb_comp_id = ccomp.id;

