
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin1",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}
###


GET {{HOSTAPI}}/api/finlote HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###


POST {{HOSTAPI}}/api/finlote HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
  "data_lote": "20/05/2001",
  "ger_empresa_id": "371eaef9-7fc6-4af4-aee9-58c830d4c9c9",
  "nome": "tst",
  "f3996813-838e-49af-9649-8dc44e24bc75"
  "sigla_fin_lote" : "tst"
}


### 




