
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
            "login":"admin",
            "password":"123",
            "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"

}
###


GET {{HOSTAPI}}/api/finpagrecbaixa HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###


POST {{HOSTAPI}}/api/finpagrecbaixa HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
  "data_baixa": "15/05/2022",
  "data_valid": "15/05/2022",
  "fin_conta_id": "adb69eb2-21f4-4914-bd4f-606109bc8093",
  "fin_doc_tipo_id": "c8e3cd09-62af-4c20-8915-21d1f36991b5",
  "fin_lote_id": "e5286575-4673-4668-9e4a-741761299fa6",
  "fin_pagrec_parc_id": "5cf246bc-8e14-455a-9388-3c9841f3394a",
  "numero_doc_pagrec": "S",
  "tipo": "N",
  "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75",
  "valor_pagrec": "5",
  "fin_pagrec_baixa_var_childs": [{
        "data_valid":"2022-12-29T00:00:00",
        "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75",
        "valor":"5",
        "observacao":"TST1",
        "fin_tipo_variacao_id":"fa12305f-c26c-44aa-98b3-c93cb1188dc7"
  }]
  
}


### 




