
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
    
}

### 
 

GET {{HOSTAPI}}/api/sysunit HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###

GET {{HOSTAPI}}/api/sysunit/90515953-eeef-47ee-bf09-ae607d76de8c HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

####


POST {{HOSTAPI}}/api/sys/sysunit HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{

"active": "S", 
"name": "ExemploX(PADRAO)", 
"code_unit": "X",
"sys_unit_manager_id":"1338cde6-3e48-4ec1-873c-5dc237d77f9b"
}


### 



DELETE {{HOSTAPI}}/api/sysunit/90515953-eeef-47ee-bf09-ae607d76de8c HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



### 





GET {{HOSTAPI}}/api/sysunit/getByUserId/f3996813-838e-49af-9649-8dc44e24bc75 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}


### 