
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin1",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}

### 

GET {{HOSTAPI}}/api/sysrestrictionlicence/a03a49db-ff32-463b-bac9-f642b80258ea HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###


POST {{HOSTAPI}}/api/sysrestrictionlicence HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{

  
    "sys_licence_id": "7aae3305-c2bb-43f1-a4e8-878f27288673",
    "sys_restriction_id": "31da7d22-1925-4f32-85cc-d578834aad3a",
    "value_restriction":"1",
      "days_blocked_extra": "1",
      "days_blocked": "2",
      "value_restriction_blocked": "1"


}


### 


POST {{HOSTAPI}}/api/sysrestrictionlicence HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{

  
  "sys_licence_id": "7aae3305-c2bb-43f1-a4e8-878f27288673",
  "sys_restriction_id": "31da7d22-1925-4f32-85cc-d578834aad3a",
  "value_restriction":"1"





