
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}

### 

GET {{HOSTAPI}}/api/sys/systranslatelang HTTP/1.1
Content-Type: application/json
//Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###

GET {{HOSTAPI}}/api/systranslatelang/16afb315-e210-42e4-9b15-ece23f5808c6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

###
POST {{HOSTAPI}}/api/sys/systranslatelang HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
    "code": "TST1",
    "name": "TST1",
    "default_lang": "S",
    "active":"S"
}


