
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}

### 


GET {{HOSTAPI}}/api/sysprogramfavorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###

GET {{HOSTAPI}}/api/sysprogramfavorite/90515953-eeef-47ee-bf09-ae607d76de8c HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

####


POST {{HOSTAPI}}/api/sys/sysprogramfavorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
"sys_program_id": "dd27cc32-fedb-4572-b09d-896663bdab7a",
 "sys_user_id":"a4a5af12-46b3-42dd-9126-bc45d5306f2b"
}


### 


GET {{HOSTAPI}}/api/sys/sysprogramfavorite/getbyuserlogin?pfilters={"filter": {"and": {"login":"admin"}}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}


####


POST {{HOSTAPI}}/api/sys/sysprogramfavorite/favorite/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
 "sys_program_id":"dd27cc32-fedb-4572-b09d-896663bdab7a",
 "sys_user_id":"062dddad-4ca3-4956-aa75-6f6cf368b05b",
 "favorite":"S"
}

### 