
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}

####

POST {{HOSTAPI}}/api/sys/sysaction HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
  "name":"View Ext",
  "code":"VIEW_",
  "active":"S"
}


### 

GET {{HOSTAPI}}/api/sys/sysaction HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

### 

GET {{HOSTAPI}}/api/sys/sysaction/96e61c78-98ad-4b5a-b747-4bde9f8aa6cd HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

### 

DELETE {{HOSTAPI}}/api/sys/sysaction/96e61c78-98ad-4b5a-b747-4bde9f8aa6cd HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}
