
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}

### 


GET {{HOSTAPI}}/api/sys/sysprocesslog?pfilters={"filter":{"and": {"date_ini_process":{"gt":"2022-11-29 13:00:00"}}, "and": {"date_ini_process":{"lt":"2022-11-29 14:00:00"}}}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}} 



###

GET {{HOSTAPI}}/api/sys/sysprocesslog/90515953-eeef-47ee-bf09-ae607d76de8c HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

####


POST {{HOSTAPI}}/api/sys/sysprocesslog HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
  "date_fin_process": "2022-11-26T00:00:00",
  "date_ini_process": "2022-10-26T00:00:00",
  "param_process": "tst",
  "reversed": "t",
  "sys_unit_id":"f3996813-838e-49af-9649-8dc44e24bc75",
  "type_process": "GER_PER_GENERATE",
  "sys_user_id":"062dddad-4ca3-4956-aa75-6f6cf368b05b",
  "message_process":"Iniciando Geração de periodo"
}


### 



DELETE {{HOSTAPI}}/api/sys/sysprocesslog/90515953-eeef-47ee-bf09-ae607d76de8c HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



### 



