import { t } from "i18next";
import { capitalize } from "../../../utils/FuncUtil";
import OpeCentroConfigService from "../../../services/modules/ope/OpeCentroConfigService";
import { IAppDataTableColumns } from "../../../components/toolkit-react/AppDataTable";
import GenericListPage from "../../generics/GenericListPage";

const opeCentroConfigService = new OpeCentroConfigService();

const OpeCentroConfig: React.FC = () => {
  const dataTableColumns: IAppDataTableColumns = {
    columns: [
      {
        appField: "id",
        appHeader: "ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
        appDataType: "text",
        appExport: true,
      },
      {
        appField: "observacao",
        appHeader: "Observação",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
      },
      {
        appField: "tipo_regra_obj.description",
        appHeader: "Tipo Régra",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_centro2_ord_tipo_id_obj.sigla_ord_tipo",
        appHeader: "Sigla ord tipo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_centro2_ord_tipo_id_obj.nome",
        appHeader: "Nome Centro2 Ord Tipo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "mov_operacao_id_obj.nome",
        appHeader: "Nome Operação",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "mov_operacao_id_obj.sigla_mov_operacao",
        appHeader: "Sigla Operação",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ger_empresa_id_obj.sigla_empresa",
        appHeader: "Sigla Empresa",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ger_empresa_id_obj.nome",
        appHeader: "Nome Empresa",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_centro1_id_obj.nome",
        appHeader: "Nome Centro 1",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_centro1_id_obj.sigla_centro1",
        appHeader: "Sigla Centro 1",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_centro2_ord_tipo_id",
        appHeader: "Centro2 Ord Tipo ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ope_centro2_id_obj.nome",
        appHeader: "Nome Centro 2",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_centro2_id_obj.sigla_centro2",
        appHeader: "Sigla Centro 2",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_atividade_id_obj.sigla_atividade",
        appHeader: "Sigla Aatividade",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_atividade_id_obj.nome",
        appHeader: "Nome Aatividade",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ger_itemserv_grupo_id_obj.sigla_ger_itemserv_grupo",
        appHeader: "Sigla Itemserv Grupo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ger_itemserv_grupo_id_obj.nome",
        appHeader: "Nome Itemserv Grupo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ger_itemserv_subgrupo_id_obj.sigla_ger_itemserv_subgrupo",
        appHeader: "Sigla Itemserv Subgrupo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ger_itemserv_subgrupo_id_obj.nome",
        appHeader: "Nome Itemserv Subgrupo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ger_itemserv_id_obj.sigla_itemserv",
        appHeader: "Sigla Itemserv",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ger_itemserv_id_obj.nome",
        appHeader: "Nome Itemserv",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_compart_grupo_id_obj.sigla_compart_grupo",
        appHeader: "Sigla Compart Grupo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_compart_grupo_id_obj.nome",
        appHeader: "Nome Compart Grupo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_compart_subgrupo_id_obj.sigla_compart_subgrupo",
        appHeader: "Sigla Compart Subgrupo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_compart_subgrupo_id_obj.nome",
        appHeader: "Nome Compart Subgrupo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_estagio_id_obj.sigla_estagio",
        appHeader: "Sigla Estagio",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_estagio_id_obj.nome",
        appHeader: "Nome Estagio",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "ope_centro_tipo_id_obj.nome",
        appHeader: "Nome Centro Tipo",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
      },
      {
        appField: "mov_operacao_id",
        appHeader: "Operação ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ger_empresa_id",
        appHeader: "Empresa ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ope_centro1_id",
        appHeader: "Centro 1 ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ope_centro2_id",
        appHeader: "Centro 2 ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ope_atividade_id",
        appHeader: "Aatividade ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ger_itemserv_grupo_id",
        appHeader: "Itemserv Grupo ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ger_itemserv_subgrupo_id",
        appHeader: "Itemserv Subgrupo ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ger_itemserv_id",
        appHeader: "Itemserv ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ope_compart_grupo_id",
        appHeader: "Compart Grupo ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ope_compart_subgrupo_id",
        appHeader: "Compart Subgrupo ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ope_centro_tipo_id",
        appHeader: "Centro Tipo ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ope_estagio_id",
        appHeader: "Estagio ID",
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
      },
      {
        appField: "ativo_obj.description",
        appHeader: capitalize(t("IN18ATIVODEFAULT")),
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: false,
        appDataType: "text",
        appExport: true,
      },
      {
        appField: "log_user_ins",
        appHeader: capitalize(t("IN18USUARIODEINSERCAODEFAULT")),
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
        appDataType: "text",
        appExport: true,
      },
      {
        appField: "log_date_ins",
        appHeader: capitalize(t("IN18DATADEINSERCAODEFAULT")),
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
        appDataType: "date",
        appExport: true,
      },
      {
        appField: "log_date_upd",
        appHeader: capitalize(t("IN18DATADEALTERACAODEFAULT")),
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
        appDataType: "date",
        appExport: true,
      },
      {
        appField: "log_user_upd",
        appHeader: capitalize(t("IN18USUARIODEALTERACAODEFAULT")),
        appSortable: true,
        appFilter: true,
        appFilterMatch: "contains",
        appFilterGlobal: true,
        appHidden: true,
        appDataType: "text",
        appExport: true,
      },
    ],
  };

  return (
    <>
      <GenericListPage
        appTitle="OPE-Centro Config"
        appShowTopBar
        appRouteForm="/private/ope/opecentroconfigform"
        appDataTableColumns={dataTableColumns}
        appDataTableDataKey="id"
        appRefreshVisible
        appDeleteVisible
        appEditVisible
        appAddVisible
        appServiceDefault={opeCentroConfigService}
      />
    </>
  );
};

export default OpeCentroConfig;
