

###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin1",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}
###


GET {{HOSTAPI}}/api/opeocor HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###


POST {{HOSTAPI}}/api/opeocor HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
    "tipo_lanc": "1",
    "nome": "tst",
    "sigla_ocor": "tst",
    "ger_umedida_id": "a1473819-04ba-438e-a129-8463084ad586",
    "icon": "tst",
    "f3996813-838e-49af-9649-8dc44e24bc75"
    "ope_ocor_grupo_id": "4a72585e-18ca-44b8-9078-ed3dbd9ba997",
    "tipo": "A",
    "ativo":"S"
}


### 




