
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{    
            "login":"admin",
            "password":"123",
            "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}
###


GET {{HOSTAPI}}/api/opecentroratfator HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###


POST {{HOSTAPI}}/api/opecentroratfator HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
    "ope_centro_subtipo_id": "0781c9d7-158e-4a1e-bf02-3f5279b0a917",
    "ctb_centro_id": "c656204d-9f55-4b00-803a-d6f42b7d4f5b",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75",
    "perc_rat": "5",
    "fator_rat": "5",
    "ope_centro1_id": "080d0a07-0171-4ba0-a825-442ab8d7b89a",
    "ope_centro_rat_periodo_id": "1087ae08-79d1-4976-8f7d-4ce741092e19",
    "ger_empresa_id": "4290a725-23c1-48dd-b6dc-3425885792c1",
    "ope_centro2_id": "b703d56e-051c-4a8e-8987-5a27349412da",
    "ope_periodo_id": "0fee9c94-de51-4bac-a6de-315ea89a49a6"
}


### 




