CREATE OR REPLACE VIEW public.vwmov_mov
AS SELECT t1.unit_id AS mov_unit_id,
    t1.id AS mov_id,
    t1.nr_externo AS mov_nr_externo,
    t1.ger_pessoa_id AS mov_ger_pessoa_id,
    t1.ger_pessoa_endereco_id_fiscal AS mov_ger_pessoa_endereco_id_fiscal,
    t1.mov_operacao_id AS mov_mov_operacao_id,
    t1.fin_cond_pagrec_id AS mov_fin_cond_pagrec_id,
    t1.data_mov AS mov_data_mov,
    t1.numero_mov AS mov_numero_mov,
    t1.data_emissao AS mov_data_emissao,
    t1.fis_doc_tipo_id AS mov_fis_doc_tipo_id,
    t1.serie_mov AS mov_serie_mov,
    t1.mov_status_id AS mov_mov_status_id,
    t1.valor_total AS mov_valor_total,
    t1.observacao AS mov_observacao,
    t1.tipo_frete AS mov_tipo_frete,
    fnstd('mov'::text, 'tipo_frete'::text, t1.tipo_frete::character varying::text) AS mov_tipo_frete_desc,
    t1.data_entrega AS mov_data_entrega,
    t1.data_entrada_saida AS mov_data_entrada_saida,
    t1.ger_pessoa_endereco_id_entrega AS mov_ger_pessoa_endereco_id_entrega,
    t1.ger_cidade_id_carreg AS mov_ger_cidade_id_carreg,
    t1.tipo_emissao_carga AS mov_tipo_emissao_carga,
    fnstd('mov'::text, 'tipo_emissao_carga'::text, t1.tipo_emissao_carga::character varying::text) AS mov_tipo_emissao_carga_desc,
    t1.tipo_modal_carga AS mov_tipo_modal_carga,
    t1.tipo_transportador_carga AS mov_tipo_transportador_carga,
    t1.valor_carga AS mov_valor_carga,
    t1.tipo_umedida_carga AS mov_tipo_umedida_carga,
    fnstd('mov'::text, 'tipo_umedida_carga'::text, t1.tipo_umedida_carga::text) AS mov_tipo_umedida_carga_desc,
    t1.qnt_carga AS mov_qnt_carga,
    t1.ger_empresa_id AS mov_empresa_id,
    t1.ger_pessoa_endereco_id_reme AS mov_pessoa_endereco_id_reme,
    t1.ger_pessoa_endereco_id_dest AS mov_pessoa_endereco_id_dest,
    t1.ger_pessoa_endereco_id_rece AS mov_pessoa_endereco_id_rece,
    t1.ger_pessoa_endereco_id_expe AS mov_pessoa_endereco_id_expe,
    t1.observacao_transp AS mov_obs_transp,
    t1.observacao_serv AS mov_obs_serv,
    t1.tipo_fretamento AS mov_tipo_fretamento,
    t1.tipo_serv_frete AS mov_tipo_serv_frete,
    t1.tipo_tomador_serv_frete AS mov_tipo_tomador_serv_frete,
    t1.taf AS mov_taf,
    t1.data_anulacao AS mov_data_anulacao,
    t1.observacao_item AS mov_observacao_item,
    t1.valor_financeiro_total AS mov_valor_financeiro_total,
    t1.valor_item_frete_total AS mov_valor_item_frete_total,
    t1.observacao_fiscal AS mov_observacao_fiscal,
    t1.ger_pessoa_endereco_id_inter AS mov_pessoa_endereco_id_inter,
    t1.fis_tipo_resp_reten AS mov_fis_tipo_resp_reten,
    fnstd('mov'::text, 'fis_tipo_resp_reten'::text, t1.fis_tipo_resp_reten::text) AS mov_fis_tipo_resp_reten_desc,
    t1.fis_exig_iss_nfs AS mov_fis_exig_iss_nfs,
    fnstd('mov'::text, 'fis_exig_iss_nfs'::text, t1.fis_exig_iss_nfs::text) AS mov_fis_exig_iss_nfs_desc,
    t1.fis_iss_retido_nfs AS mov_fis_iss_retido_nfs,
    fnstd('SN'::text, 'default'::text, t1.fis_iss_retido_nfs::text) AS mov_fis_iss_retido_nfs_desc,
    t1.fis_nat_ope_nfs AS mov_fis_nat_ope_nfs,
    fnstd('mov'::text, 'fis_nat_ope_nfs'::text, t1.fis_nat_ope_nfs::text) AS mov_fis_nat_ope_nfs_desc,
    t1.numero_mov_pre AS mov_numero_mov_pre,
    t1.serio_mov_pre AS mov_serio_mov_pre,
    t1.cep_carreg AS mov_cep_carreg,
    t1.cep_descarreg AS mov_cep_descarreg,
    t1.tipo_carga AS mov_tipo_carga,
    fnstd('mov'::text, 'tipo_carga'::text, t1.tipo_carga::text) AS mov_tipo_carga_desc,
    t1.system_user_id_resp AS mov_system_user_id_resp,
    t2.id AS ger_pessoa_id,
    t2.nome AS ger_pessoa_nome,
    t2.ativo AS ger_pessoa_ativo,
    fnstd('SN'::text, 'default'::text, t2.ativo::text) AS ger_pessoa_ativo_desc,
    t2.doc_cpf AS ger_pessoa_doc_cpf,
    t2.doc_cnpj AS ger_pessoa_doc_cnpj,
    fnutil_formatcpfcnpj(t2.id, true) AS ger_pessoa_doc_cpf_cnpj_desc,
    t2.sigla_pes AS ger_pessoa_sigla_pes,
    t2.fone_1 AS ger_pessoa_fone_1,
    t2.contato_1 AS ger_pessoa_contato_1,
    t3.id AS ger_pessoa_endereco_id,
    t3.ativo AS ger_pessoa_endereco_ativo,
    fnstd('SN'::text, 'default'::text, t3.ativo::text) AS ger_pessoa_endereco_ativo_desc,
    t3.tipo AS ger_pessoa_endereco_tipo,
    fnstd('ger_pessoa_endereco'::text, 'tipo'::text, t3.tipo::text) AS ger_pessoa_endereco_tipo_desc,
    t3.padrao AS ger_pessoa_endereco_padrao,
    fnstd('SN'::text, 'default'::text, t3.padrao::text) AS ger_pessoa_endereco_padrao_desc,
    t3.end_logradouro AS ger_pessoa_endereco_end_lograd,
    t3.end_logradouro_nr AS ger_pessoa_endereco_lograd_nr,
    t3.end_bairro AS ger_pessoa_endereco_end_bairro,
    t3.end_cep AS ger_pessoa_endereco_end_cep,
    t4.id AS mov_operacao_id,
    t4.nome AS mov_operacao_nome,
    t4.ativo AS mov_operacao_ativo,
    fnstd('SN'::text, 'default'::text, t4.ativo::text) AS mov_operacao_ativo_desc,
    t4.sigla_mov_operacao AS mov_operacao_sigla,
    t4.finalidade_doc AS mov_operacao_finalidade_doc,
    t4.tipo_es AS mov_operacao_tipo_es,
    fnstd('default'::text, 'tipo_es'::text, t4.tipo_es::text) AS mov_operacao_tipo_es_desc,
    t5.id AS mov_tipo_id,
    t5.nome AS mov_tipo_nome,
    t5.ativo AS mov_tipo_ativo,
    fnstd('SN'::text, 'default'::text, t5.ativo::text) AS mov_tipo_ativo_desc,
    t5.sigla_mov_tipo AS mov_tipo_sigla,
    t5.tipo_mov AS mov_tipo_tipo_mov,
    t6.id AS ger_numeracao_id,
    t6.nome AS ger_numeracao_nome,
    t6.ativo AS ger_numeracao_ativo,
    fnstd('SN'::text, 'default'::text, t6.ativo::text) AS ger_numeracao_ativo_desc,
    t6.serie AS ger_numeracao_serie,
    t6.ultimo_nr AS ger_numeracao_ultimo_nr,
    t7.id AS fin_cond_pagrec_id,
    t7.nome AS fin_cond_pagrec_nome,
    t7.ativo AS fin_cond_pagrec_ativo,
    fnstd('SN'::text, 'default'::text, t7.ativo::text) AS fin_cond_pagrec_ativo_desc,
    t7.sigla_cond_pagamento AS fin_cond_pagrec_sigla,
    t7.considera_feriado AS fin_cond_pagrec_considera_feriado,
    fnstd('SN'::text, 'default'::text, t7.considera_feriado::text) AS fin_cond_pagrec_considera_feriado_desc,
    t7.considera_final_sem AS fin_cond_pagrec_considera_final_sem,
    fnstd('SN'::text, 'default'::text, t7.considera_final_sem::text) AS fin_cond_pagrec_considera_final_sem_desc,
    t7.qnt_dia_ini AS fin_cond_pagrec_qnt_dia_ini,
    t7.observacao AS fin_cond_pagrec_obs,
    t7.tipo_prazo AS fin_cond_pagrec_tipo_prazo,
    t8.id AS fis_doc_tipo_id,
    t8.nome AS fis_doc_tipo_nome,
    t8.ativo AS fis_doc_tipo_ativo,
    fnstd('SN'::text, 'default'::text, t8.ativo::text) AS fis_doc_tipo_ativo_desc,
    t8.modelo AS fis_doc_tipo_modelo,
    t9.id AS mov_status_id,
    t9.nome AS mov_status_nome,
    t9.ativo AS mov_status_ativo,
    fnstd('SN'::text, 'default'::text, t9.ativo::text) AS mov_status_ativo_desc,
    t9.sigla_mov_status AS mov_status_sigla,
    t9.tipo_status AS mov_status_tipo_status,
    fnstd('mov_status'::text, 'tipo_status'::text, t9.tipo_status::text) AS mov_status_tipo_status_desc,
    t10.id AS ger_pessoa_endereco_entrega_id,
    t10.ativo AS ger_pessoa_endereco_entrega_ativo,
    fnstd('SN'::text, 'default'::text, t10.ativo::text) AS ger_pessoa_endereco_entrega_ativo_desc,
    t10.tipo AS ger_pessoa_endereco_entrega_tipo,
    fnstd('ger_pessoa_endereco'::text, 'tipo'::text, t10.tipo::text) AS ger_pessoa_endereco_entrega_tipo_desc,
    t10.padrao AS ger_pessoa_endereco_entrega_padrao,
    fnstd('SN'::text, 'default'::text, t10.padrao::text) AS ger_pessoa_endereco_entrega_padrao_desc,
    t10.end_logradouro AS ger_pessoa_endereco_entrega_end_lograd,
    t10.end_logradouro_nr AS ger_pessoa_endereco_entrega_end_lograd_nr,
    t10.end_bairro AS ger_pessoa_endereco_entrega_end_bairro,
    t10.end_complemento AS ger_pessoa_endereco_entrega_end_complemento,
    t10.end_cep AS ger_pessoa_endereco_entrega_end_cep,
    t11.id AS ger_pessoa_entrega_id,
    t11.nome AS ger_pessoa_entrega_nome,
    t11.ativo AS ger_pessoa_entrega_ativo,
    fnstd('SN'::text, 'default'::text, t11.ativo::text) AS ger_pessoa_entrega_ativo_desc,
    t11.doc_cpf AS ger_pessoa_entrega_doc_cpf,
    t11.doc_cnpj AS ger_pessoa_entrega_doc_cnpj,
    fnutil_formatcpfcnpj(t11.id, true) AS ger_pessoa_entrega_doc_cpf_cnpj_desc,
    t11.sigla_pes AS ger_pessoa_entrega_sigla,
    t12.id AS ger_cidade_carreg_id,
    t12.nome AS ger_cidade_carreg_nome,
    t12.ativo AS ger_cidade_carreg_ativo,
    fnstd('SN'::text, 'default'::text, t12.ativo::text) AS ger_cidade_carreg_ativo_desc,
    t12.nr_cidade AS ger_cidade_carreg_nr_cidade,
    t13.id AS ger_uf_carreg_id,
    t13.nome AS ger_uf_carreg_nome,
    t13.ativo AS ger_uf_carreg_ativo,
    fnstd('SN'::text, 'default'::text, t13.ativo::text) AS ger_uf_carreg_ativo_desc,
    t13.nr_uf AS ger_uf_carreg_nr_uf,
    t13.sigla_uf AS ger_uf_carreg_sigla,
    t14.id AS ger_cidade_descarreg_id,
    t14.nome AS ger_cidade_descarreg_nome,
    t14.ativo AS ger_cidade_descarreg_ativo,
    fnstd('SN'::text, 'default'::text, t14.ativo::text) AS ger_cidade_descarreg_ativo_desc,
    t14.nr_cidade AS ger_cidade_descarreg_nr_cidade,
    t15.id AS ger_uf_descarreg_id,
    t15.nome AS ger_uf_descarreg_nome,
    t15.ativo AS ger_uf_descarreg_ativo,
    fnstd('SN'::text, 'default'::text, t15.ativo::text) AS ger_uf_descarreg_ativo_desc,
    t15.nr_uf AS ger_uf_descarreg_nr_uf,
    t15.sigla_uf AS ger_uf_descarreg_sigla,
    t16.id AS ger_empresa_id,
    t16.nome AS ger_empresa_nome,
    t16.ativo AS ger_empresa_ativo,
    fnstd('SN'::text, 'default'::text, t16.ativo::text) AS ger_empresa_ativo_desc,
    t16.sigla_empresa AS ger_empresa_sigla,
    t17.id AS ger_pessoa_endereco_reme_id,
    t17.ativo AS ger_pessoa_endereco_reme_ativo,
    fnstd('SN'::text, 'default'::text, t17.ativo::text) AS ger_pessoa_endereco_reme_ativo_desc,
    t17.tipo AS ger_pessoa_endereco_reme_tipo,
    fnstd('ger_pessoa_endereco'::text, 'tipo'::text, t17.tipo::text) AS ger_pessoa_endereco_reme_tipo_desc,
    t17.padrao AS ger_pessoa_endereco_reme_padrao,
    fnstd('SN'::text, 'default'::text, t17.padrao::text) AS ger_pessoa_endereco_reme_padrao_desc,
    t17.end_logradouro AS ger_pessoa_endereco_reme_end_lograd,
    t17.end_logradouro_nr AS ger_pessoa_endereco_reme_end_lograd_nr,
    t17.end_bairro AS ger_pessoa_endereco_reme_end_bairro,
    t17.end_complemento AS ger_pessoa_endereco_reme_end_complemento,
    t17.end_cep AS ger_pessoa_endereco_reme_end_cep,
    t18.id AS ger_pessoa_reme_id,
    t18.nome AS ger_pessoa_reme_nome,
    t18.ativo AS ger_pessoa_reme_ativo,
    fnstd('SN'::text, 'default'::text, t18.ativo::text) AS ger_pessoa_reme_ativo_desc,
    t18.doc_cpf AS ger_pessoa_reme_doc_cpf,
    t18.doc_cnpj AS ger_pessoa_reme_doc_cnpj,
    fnutil_formatcpfcnpj(t18.id, true) AS ger_pessoa_reme_doc_cpf_cnpj_desc,
    t18.sigla_pes AS ger_pessoa_reme_sigla,
    t19.id AS ger_pessoa_endereco_dest_id,
    t19.ativo AS ger_pessoa_endereco_dest_ativo,
    fnstd('SN'::text, 'default'::text, t19.ativo::text) AS ger_pessoa_endereco_dest_ativo_desc,
    t19.tipo AS ger_pessoa_endereco_dest_tipo,
    fnstd('ger_pessoa_endereco'::text, 'tipo'::text, t19.tipo::text) AS ger_pessoa_endereco_dest_tipo_desc,
    t19.padrao AS ger_pessoa_endereco_dest_padrao,
    fnstd('SN'::text, 'default'::text, t19.padrao::text) AS ger_pessoa_endereco_dest_padrao_desc,
    t19.end_logradouro AS ger_pessoa_endereco_dest_end_lograd,
    t19.end_logradouro_nr AS ger_pessoa_endereco_dest_end_lograd_nr,
    t19.end_bairro AS ger_pessoa_endereco_dest_end_bairro,
    t19.end_complemento AS ger_pessoa_endereco_dest_end_complemento,
    t19.end_cep AS ger_pessoa_endereco_dest_end_cep,
    t20.id AS ger_pessoa_dest_id,
    t20.nome AS ger_pessoa_dest_nome,
    t20.ativo AS ger_pessoa_dest_ativo,
    fnstd('SN'::text, 'default'::text, t20.ativo::text) AS ger_pessoa_dest_ativo_desc,
    t20.doc_cpf AS ger_pessoa_dest_doc_cpf,
    t20.doc_cnpj AS ger_pessoa_dest_doc_cnpj,
    fnutil_formatcpfcnpj(t20.id, true) AS ger_pessoa_dest_doc_cpf_cnpj_desc,
    t20.sigla_pes AS ger_pessoa_dest_sigla,
    t21.id AS ger_pessoa_endereco_rece_id,
    t21.ativo AS ger_pessoa_endereco_rece_ativo,
    fnstd('SN'::text, 'default'::text, t21.ativo::text) AS ger_pessoa_endereco_rece_ativo_desc,
    t21.tipo AS ger_pessoa_endereco_rece_tipo,
    fnstd('ger_pessoa_endereco'::text, 'tipo'::text, t21.tipo::text) AS ger_pessoa_endereco_rece_tipo_desc,
    t21.padrao AS ger_pessoa_endereco_rece_padrao,
    fnstd('SN'::text, 'default'::text, t21.padrao::text) AS ger_pessoa_endereco_rece_padrao_desc,
    t21.end_logradouro AS ger_pessoa_endereco_rece_end_lograd,
    t21.end_logradouro_nr AS ger_pessoa_endereco_rece_end_lograd_nr,
    t21.end_bairro AS ger_pessoa_endereco_rece_end_bairro,
    t21.end_complemento AS ger_pessoa_endereco_rece_end_complemento,
    t21.end_cep AS ger_pessoa_endereco_rece_end_cep,
    t22.id AS ger_pessoa_rece_id,
    t22.nome AS ger_pessoa_rece_nome,
    t22.ativo AS ger_pessoa_rece_ativo,
    fnstd('SN'::text, 'default'::text, t22.ativo::text) AS ger_pessoa_rece_ativo_desc,
    t22.doc_cpf AS ger_pessoa_rece_doc_cpf,
    t22.doc_cnpj AS ger_pessoa_rece_doc_cnpj,
    fnutil_formatcpfcnpj(t22.id, true) AS ger_pessoa_rece_doc_cpf_cnpj_desc,
    t22.sigla_pes AS ger_pessoa_rece_sigla,
    t23.id AS ger_pessoa_endereco_expe_id,
    t23.ativo AS ger_pessoa_endereco_expe_ativo,
    fnstd('SN'::text, 'default'::text, t23.ativo::text) AS ger_pessoa_endereco_expe_ativo_desc,
    t23.tipo AS ger_pessoa_endereco_expe_tipo,
    fnstd('ger_pessoa_endereco'::text, 'tipo'::text, t23.tipo::text) AS ger_pessoa_endereco_expe_tipo_desc,
    t23.padrao AS ger_pessoa_endereco_expe_padrao,
    fnstd('SN'::text, 'default'::text, t23.padrao::text) AS ger_pessoa_endereco_expe_padrao_desc,
    t23.end_logradouro AS ger_pessoa_endereco_expe_end_lograd,
    t23.end_logradouro_nr AS ger_pessoa_endereco_expe_end_lograd_nr,
    t23.end_bairro AS ger_pessoa_endereco_expe_end_bairro,
    t23.end_complemento AS ger_pessoa_endereco_expe_end_complemento,
    t23.end_cep AS ger_pessoa_endereco_expe_end_cep,
    t24.id AS ger_pessoa_expe_id,
    t24.nome AS ger_pessoa_expe_nome,
    t24.ativo AS ger_pessoa_expe_ativo,
    fnstd('SN'::text, 'default'::text, t24.ativo::text) AS ger_pessoa_expe_ativo_desc,
    t24.doc_cpf AS ger_pessoa_expe_doc_cpf,
    t24.doc_cnpj AS ger_pessoa_expe_doc_cnpj,
    fnutil_formatcpfcnpj(t24.id, true) AS ger_pessoa_expe_doc_cpf_cnpj_desc,
    t24.sigla_pes AS ger_pessoa_expe_sigla,
    t25.id AS ger_pessoa_endereco_inter_id,
    t25.ativo AS ger_pessoa_endereco_inter_ativo,
    fnstd('SN'::text, 'default'::text, t25.ativo::text) AS ger_pessoa_endereco_inter_ativo_desc,
    t25.tipo AS ger_pessoa_endereco_inter_tipo,
    fnstd('ger_pessoa_endereco'::text, 'tipo'::text, t25.tipo::text) AS ger_pessoa_endereco_inter_tipo_desc,
    t25.padrao AS ger_pessoa_endereco_inter_padrao,
    fnstd('SN'::text, 'default'::text, t25.padrao::text) AS ger_pessoa_endereco_inter_padrao_desc,
    t25.end_logradouro AS ger_pessoa_endereco_inter_end_lograd,
    t25.end_logradouro_nr AS ger_pessoa_endereco_inter_end_lograd_nr,
    t25.end_bairro AS ger_pessoa_endereco_inter_end_bairro,
    t25.end_complemento AS ger_pessoa_endereco_inter_end_complemento,
    t25.end_cep AS ger_pessoa_endereco_inter_end_cep,
    t26.id AS ger_pessoa_inter_id,
    t26.nome AS ger_pessoa_inter_nome,
    t26.ativo AS ger_pessoa_inter_ativo,
    fnstd('SN'::text, 'default'::text, t26.ativo::text) AS ger_pessoa_inter_ativo_desc,
    t26.doc_cpf AS ger_pessoa_inter_doc_cpf,
    t26.doc_cnpj AS ger_pessoa_inter_doc_cnpj,
    fnutil_formatcpfcnpj(t26.id, true) AS ger_pessoa_inter_doc_cpf_cnpj_desc,
    t26.sigla_pes AS ger_pessoa_inter_sigla,
    t27.id AS system_user_id,
    t27.name AS system_user_name,
    t27.login AS system_user_login,
    t27.active AS system_user_ativo,
    fnstd('SN'::text, 'default'::text, t27.active::text) AS system_user_ativo_desc,
    t27.phone AS system_user_phone,
    t1.log_user_ins,
    t1.log_date_ins,
    t1.log_user_upd,
    t1.log_date_upd,
    (t2.sigla_pes::text || ' - '::text) || t2.nome::text AS ger_pessoa_sigla_pes_desc,
    (t4.sigla_mov_operacao::text || ' - '::text) || t4.nome::text AS mov_operacao_sigla_desc,
    (t5.sigla_mov_tipo::text || ' - '::text) || t5.nome::text AS mov_tipo_sigla_desc,
    (t7.sigla_cond_pagamento::text || ' - '::text) || t7.nome::text AS fin_cond_pagrec_sigla_desc,
    (t9.sigla_mov_status::text || ' - '::text) || t9.nome::text AS mov_status_sigla_desc,
    (t11.sigla_pes::text || ' - '::text) || t11.nome::text AS ger_pessoa_entrega_sigla_desc,
    (t13.sigla_uf::text || ' - '::text) || t13.nome::text AS ger_uf_carreg_sigla_desc,
    (t15.sigla_uf::text || ' - '::text) || t15.nome::text AS ger_uf_descarreg_sigla_desc,
    (t16.sigla_empresa::text || ' - '::text) || t16.nome::text AS ger_empresa_sigla_desc,
    (t18.sigla_pes::text || ' - '::text) || t18.nome::text AS ger_pessoa_reme_sigla_desc,
    (t20.sigla_pes::text || ' - '::text) || t20.nome::text AS ger_pessoa_dest_sigla_desc,
    (t22.sigla_pes::text || ' - '::text) || t22.nome::text AS ger_pessoa_rece_sigla_desc,
    (t24.sigla_pes::text || ' - '::text) || t24.nome::text AS ger_pessoa_expe_sigla_desc,
    (t26.sigla_pes::text || ' - '::text) || t26.nome::text AS ger_pessoa_inter_sigla_desc
   FROM mov t1
     JOIN ger_pessoa t2 ON t1.ger_pessoa_id::text = t2.id::text
     JOIN ger_pessoa_endereco t3 ON t1.ger_pessoa_endereco_id_fiscal::text = t3.id::text
     LEFT JOIN mov_operacao t4 ON t1.mov_operacao_id::text = t4.id::text
     JOIN mov_tipo t5 ON t4.mov_tipo_id::text = t5.id::text
     JOIN ger_numeracao t6 ON t4.ger_numeracao_id::text = t6.id::text
     LEFT JOIN fin_cond_pagrec t7 ON t1.fin_cond_pagrec_id::text = t7.id::text
     LEFT JOIN fis_doc_tipo t8 ON t1.fis_doc_tipo_id::text = t8.id::text
     LEFT JOIN mov_status t9 ON t1.mov_status_id::text = t9.id::text
     JOIN ger_pessoa_endereco t10 ON t1.ger_pessoa_endereco_id_entrega::text = t10.id::text
     JOIN ger_pessoa t11 ON t10.ger_pessoa_id::text = t11.id::text
     LEFT JOIN ger_cidade t12 ON t1.ger_cidade_id_carreg::text = t12.id::text
     LEFT JOIN ger_uf t13 ON t12.ger_uf_id::text = t13.id::text
     LEFT JOIN ger_cidade t14 ON t1.ger_cidade_id_descarreg::text = t14.id::text
     LEFT JOIN ger_uf t15 ON t14.ger_uf_id::text = t15.id::text
     JOIN ger_empresa t16 ON t1.ger_empresa_id::text = t16.id::text
     LEFT JOIN ger_pessoa_endereco t17 ON t1.ger_pessoa_endereco_id_reme::text = t17.id::text
     LEFT JOIN ger_pessoa t18 ON t17.ger_pessoa_id::text = t18.id::text
     LEFT JOIN ger_pessoa_endereco t19 ON t1.ger_pessoa_endereco_id_dest::text = t19.id::text
     LEFT JOIN ger_pessoa t20 ON t19.ger_pessoa_id::text = t20.id::text
     LEFT JOIN ger_pessoa_endereco t21 ON t1.ger_pessoa_endereco_id_rece::text = t21.id::text
     LEFT JOIN ger_pessoa t22 ON t21.ger_pessoa_id::text = t22.id::text
     LEFT JOIN ger_pessoa_endereco t23 ON t1.ger_pessoa_endereco_id_expe::text = t23.id::text
     LEFT JOIN ger_pessoa t24 ON t23.ger_pessoa_id::text = t24.id::text
     LEFT JOIN ger_pessoa_endereco t25 ON t1.ger_pessoa_endereco_id_inter::text = t25.id::text
     LEFT JOIN ger_pessoa t26 ON t25.ger_pessoa_id::text = t26.id::text
     LEFT JOIN system_user t27 ON t1.system_user_id_resp::text = t27.id::text;