DROP VIEW IF EXISTS vwope_ocor_mov_dest_equip;
CREATE OR REPLACE VIEW vwope_ocor_mov_dest_equip AS 
SELECT
	t1.unit_id,
	t1.ID AS ope_ocor_mov_dest_id,
	t1.observacao AS ope_ocor_mov_dest_obs,
	t1.ope_centro2_id AS ope_ocor_mov_dest_centro2_id,
---------------------------------------------------
	t2.ope_ocor_mov_id,
	t2.ope_ocor_mov_obs,
	t2.ope_ocor_mov_data_mov,
	t2.ope_ocor_mov_numero,
	t2.ope_ocor_mov_ger_empresa_id,
	t2.ope_ocor_mov_pes_endereco_id_exec,
	t2.ope_ocor_mov_ocor_tipo_id,
	t2.ger_empresa_id,
	t2.ger_empresa_nome,
	t2.ger_empresa_razao_social,
	t2.ger_empresa_ativo,
	t2.ger_empresa_ativo_desc,
	t2.ger_empresa_sigla,
	t2.ger_empresa_doc_cnpj,
	t2.ger_empresa_doc_cpf,
	t2.ger_pessoa_endereco_id,
	t2.ger_pessoa_endereco,
	t2.ger_pessoa_endereco_nr,
	t2.ger_pessoa_endereco_cep,
	t2.ger_pessoa_endereco_id_cidade,
	t2.ger_pessoa_endereco_nome_cidade,
	t2.ger_pessoa_endereco_uf,
	t2.ger_pessoa_endereco_id_pes,
	t2.ger_pessoa_endereco_nome_pes,
	t2.ger_pessoa_endereco_doc_pes,
	t2.ope_ocor_tipo_id,
	t2.ope_ocor_tipo_nome,
	t2.ope_ocor_tipo_ativo,
	t2.ope_ocor_tipo_ativo_desc,
	t2.ope_ocor_tipo_sigla,
	t2.ope_ocor_tipo_tp,
	t2.ope_ocor_tipo_tp_desc,
	t2.ope_ocor_tipo_obrig,
	t2.ope_ocor_tipo_obrig_desc,
	t2.ope_ocor_mov_det_id,
	t2.ope_ocor_mov_det_obs,
	t2.ope_ocor_mov_det_qnt_ocor,
	t2.ope_ocor_mov_det_qnt_ocor_calc,
	t2.ope_ocor_mov_det_data_status,
	t2.ope_ocor_mov_det_qnt_ocor_long_y,
	t2.ope_ocor_mov_det_qnt_ocor_lat_x,
	t2.ope_ocor_mov_det_ocor_ponto,
	t2.ope_ocor_id,
	t2.ope_ocor_nome,
	t2.ope_ocor_ativo,
	t2.ope_ocor_ativo_desc,
	t2.ope_ocor_sigla,
	t2.ope_ocor_icon,
	t2.ope_ocor_tipo,
	t2.ope_ocor_tipo_desc,
	t2.ope_ocor_tipo_lanc,
	t2.ope_ocor_tipo_lanc_desc,
	t2.ope_ocor_grupo_id,
	t2.ope_ocor_grupo_nome,
	t2.ope_ocor_grupo_ativo,
	t2.ope_ocor_grupo_ativo_desc,
	t2.ope_ocor_grupo_sigla,
	t2.ger_umedida_id,
	t2.ger_umedida_nome,
	t2.ger_umedida_ativo,
	t2.ger_umedida_ativo_desc,
	t2.ger_umedida_sigla,
	t2.ope_ocor_status_id,
	t2.ope_ocor_status_nome,
	t2.ope_ocor_status_ativo,
	t2.ope_ocor_status_sigla,
	t2.ope_ocor_status_tipo_status,
	t2.ope_ocor_status_tipo_status_desc,
	t2.ger_empresa_sigla_desc,
	t2.ope_ocor_tipo_sigla_desc,
	t2.ope_ocor_sigla_desc,
	t2.ope_ocor_grupo_sigla_desc,
	t2.ger_umedida_sigla_desc,
	t2.ope_ocor_status_sigla_desc,
------------------------------------------------------
	t3.ID AS ope_compart_id,
	t3.nome AS ope_compart_nome,
	t3.ativo AS ope_compart_ativo,
	t3.sigla_compart AS ope_compart_sigla,
	t3.capacidade AS ope_compart_capacidade,
	t3.valida_itemserv AS ope_compart_validade_itemserv,
	t3.medicao_trab_centro AS ope_compart_medicao_trab_centro,
	t3.data_aquisicao AS ope_compart_data_aquisicao,
	t3.data_baixa AS ope_compart_data_baixa,
	data_status AS ope_compart_data_status,
	t3.observacao AS ope_compart_obs,
	t3.valor_aquisicao AS ope_compart_vr_aquisicao,
	t3.numero_serie AS ope_compart_nr_serie,
--------------------------------------------------------
	t4.ope_centro1_id,
	t4.ope_centro1_sigla,
	t4.ope_centro1_nome,
	t4.ope_centro1_ativo,
	t4.ope_centro1_ativo_desc,
	t4.ope_centro2_id,
	t4.ope_centro2_nome,
	t4.ope_centro2_ativo,
	t4.ope_centro2_ativo_desc,
	t4.ope_centro2_sigla,
	t4.ope_centro2_equip_id,
	t4.ope_centro2_equip_tipo_rodado,
	t4.ope_centro2_equip_tipo_rodado_desc,
	t4.ope_centro2_equip_tipo_carroceria,
	t4.ope_centro2_equip_tipo_carroceria_desc,
	t4.ope_centro2_equip_cidade_id,
	t4.ope_centro2_equip_cidade_nome,
	t4.ope_centro2_equip_cidade_ativo,
	t4.ope_centro2_equip_cidade_ativo_desc,
	t4.ope_centro2_uf_id,
	t4.ope_centro2_uf_nome,
	t4.ope_centro2_uf_sigla,
	t4.ope_centro2_equip_placa,
	t4.ope_centro2_equip_renavam,
	t4.ope_centro2_equip_tara,
	t4.ope_centro2_equip_capacidade_kg,
	t4.ope_centro2_equip_capacidade_m3,
	t4.ope_centro2_equip_potencia,
	t4.ope_centro2_equip_nr_chassi,
	t4.ope_centro2_equip_nr_serie,
	t4.ope_centro2_equip_liberado_abastec,
	t4.ope_centro2_equip_liberado_abastec_desc,
	t4.ope_centro2_equip_largura,
	t4.ope_centro2_equip_altura,
	t4.ope_centro2_equip_nr_registro_estadual,
	t4.ope_centro2_equip_tipo_tracao,
	t4.ope_centro2_equip_tipo_tracao_desc,
	t4.ope_centro2_equip_tipo_transp_auto_carga,
	t4.ope_centro2_equip_tipo_transp_auto_carga_desc,
--------------------------------------------------------
	t1.log_user_ins,
	t1.log_date_ins,
	t1.log_user_upd,
	t1.log_date_upd 
FROM
	ope_ocor_mov_dest t1
	INNER JOIN vwope_ocor_mov t2 
	ON t1.ope_ocor_mov_id = t2.ope_ocor_mov_id
	LEFT JOIN ope_compart t3 
	ON t1.ope_compart_id = t3.id 
	INNER JOIN vwope_centro2_equip t4 
	ON t1.ope_centro2_id = t4.ope_centro2_id
	