
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin1",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}

### 
GET {{HOSTAPI}}/api/geritemservbarra HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}
###


POST {{HOSTAPI}}/api/geritemservbarra HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
  "codigo_barra":"tst",
  "ger_itemserv_id":"23eb3a91-7200-477e-9eb5-772e255928f3",
  "unit_id":"117bc5eb-2185-4b10-bcdc-9eb20ad534e1",
  "ativo":"S"
}


### 



POST {{HOSTAPI}}/api/geritemservbarra HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
  "codigo_barra":"",
  "ger_itemserv_id":"",
  "unit_id":""
}

### 



