
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin1",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}

### 
GET {{HOSTAPI}}/api/geritemservcompostipo HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}
###
POST {{HOSTAPI}}/api/geritemservcompostipo HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
 "nome":"tst",
  "unit_id":"c9d4f32b-113c-4eb9-9293-4399749733b7",
  "sigla_ger_itemserv_compos_tipo":"TST"
}


### 




