
###
@HOSTAPI=http://127.0.0.1:5000

### 

# @name TOKEN_REST
POST {{HOSTAPI}}/api/auth/login HTTP/1.1
Content-Type: application/json

{   
    "login":"admin1",
    "password":"123",
    "unit_id":"f3996813-838e-49af-9649-8dc44e24bc75"
}
###


GET {{HOSTAPI}}/api/movoperacaostatus HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}



###


POST {{HOSTAPI}}/api/movoperacaostatus HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.access_token}}

{
    "mov_operacao_id": "14bbd386-d488-4c46-9bba-5e8faa2f1f37",
    "mov_status_id_prox": "ffe70930-f11b-4c00-9fe1-2b3bedee9bc4",
    "f3996813-838e-49af-9649-8dc44e24bc75"
    "mov_operacao_id_prox": "14bbd386-d488-4c46-9bba-5e8faa2f1f37",
    "mov_status_id": "ffe70930-f11b-4c00-9fe1-2b3bedee9bc4"
}


### 




